// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.2
// source: sts.proto

package sts

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	STSService_AssumeRole_FullMethodName               = "/sts.STSService/AssumeRole"
	STSService_GetSessionToken_FullMethodName          = "/sts.STSService/GetSessionToken"
	STSService_GetFederationToken_FullMethodName       = "/sts.STSService/GetFederationToken"
	STSService_LookupUserByAccessKey_FullMethodName    = "/sts.STSService/LookupUserByAccessKey"
	STSService_DecryptSecretKey_FullMethodName         = "/sts.STSService/DecryptSecretKey"
	STSService_LookupTempCredential_FullMethodName     = "/sts.STSService/LookupTempCredential"
	STSService_LookupUser_FullMethodName               = "/sts.STSService/LookupUser"
	STSService_EvaluateAccess_FullMethodName           = "/sts.STSService/EvaluateAccess"
	STSService_AdminCreateUser_FullMethodName          = "/sts.STSService/AdminCreateUser"
	STSService_AdminDeleteUser_FullMethodName          = "/sts.STSService/AdminDeleteUser"
	STSService_AdminListUsers_FullMethodName           = "/sts.STSService/AdminListUsers"
	STSService_AdminCreateAccessKey_FullMethodName     = "/sts.STSService/AdminCreateAccessKey"
	STSService_AdminListAccessKeys_FullMethodName      = "/sts.STSService/AdminListAccessKeys"
	STSService_AdminDeleteAccessKey_FullMethodName     = "/sts.STSService/AdminDeleteAccessKey"
	STSService_AdminListGroups_FullMethodName          = "/sts.STSService/AdminListGroups"
	STSService_AdminCreateGroup_FullMethodName         = "/sts.STSService/AdminCreateGroup"
	STSService_AdminDeleteGroup_FullMethodName         = "/sts.STSService/AdminDeleteGroup"
	STSService_AdminAddUserToGroup_FullMethodName      = "/sts.STSService/AdminAddUserToGroup"
	STSService_AdminRemoveUserFromGroup_FullMethodName = "/sts.STSService/AdminRemoveUserFromGroup"
	STSService_AdminListPolicies_FullMethodName        = "/sts.STSService/AdminListPolicies"
	STSService_AdminCreatePolicy_FullMethodName        = "/sts.STSService/AdminCreatePolicy"
	STSService_AdminDeletePolicy_FullMethodName        = "/sts.STSService/AdminDeletePolicy"
	STSService_AdminAttachUserPolicy_FullMethodName    = "/sts.STSService/AdminAttachUserPolicy"
	STSService_AdminDetachUserPolicy_FullMethodName    = "/sts.STSService/AdminDetachUserPolicy"
	STSService_AdminAttachGroupPolicy_FullMethodName   = "/sts.STSService/AdminAttachGroupPolicy"
	STSService_AdminListRoles_FullMethodName           = "/sts.STSService/AdminListRoles"
	STSService_AdminCreateRole_FullMethodName          = "/sts.STSService/AdminCreateRole"
	STSService_AdminDeleteRole_FullMethodName          = "/sts.STSService/AdminDeleteRole"
	STSService_AdminAttachRolePolicy_FullMethodName    = "/sts.STSService/AdminAttachRolePolicy"
	STSService_AdminGetBucketPolicy_FullMethodName     = "/sts.STSService/AdminGetBucketPolicy"
	STSService_AdminPutBucketPolicy_FullMethodName     = "/sts.STSService/AdminPutBucketPolicy"
	STSService_AdminDeleteBucketPolicy_FullMethodName  = "/sts.STSService/AdminDeleteBucketPolicy"
	STSService_AdminSimulatePolicy_FullMethodName      = "/sts.STSService/AdminSimulatePolicy"
)

// STSServiceClient is the client API for STSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// STS Service - Security Token Service + IAM Lookup
type STSServiceClient interface {
	// AssumeRole returns temporary credentials for an assumed role
	AssumeRole(ctx context.Context, in *AssumeRoleRequest, opts ...grpc.CallOption) (*AssumeRoleResponse, error)
	// GetSessionToken returns temporary credentials for the current user
	GetSessionToken(ctx context.Context, in *GetSessionTokenRequest, opts ...grpc.CallOption) (*GetSessionTokenResponse, error)
	// GetFederationToken returns temporary credentials for a federated user
	GetFederationToken(ctx context.Context, in *GetFederationTokenRequest, opts ...grpc.CallOption) (*GetFederationTokenResponse, error)
	// LookupUserByAccessKey finds a user by access key ID
	LookupUserByAccessKey(ctx context.Context, in *LookupUserByAccessKeyRequest, opts ...grpc.CallOption) (*LookupUserByAccessKeyResponse, error)
	// DecryptSecretKey decrypts an encrypted secret key
	DecryptSecretKey(ctx context.Context, in *DecryptSecretKeyRequest, opts ...grpc.CallOption) (*DecryptSecretKeyResponse, error)
	// LookupTempCredential finds a temporary credential by access key ID
	LookupTempCredential(ctx context.Context, in *LookupTempCredentialRequest, opts ...grpc.CallOption) (*LookupTempCredentialResponse, error)
	// LookupUser finds a user by name
	LookupUser(ctx context.Context, in *LookupUserRequest, opts ...grpc.CallOption) (*LookupUserResponse, error)
	// EvaluateAccess evaluates IAM policy for a request
	EvaluateAccess(ctx context.Context, in *EvaluateAccessRequest, opts ...grpc.CallOption) (*EvaluateAccessResponse, error)
	// AdminCreateUser creates a new IAM user
	AdminCreateUser(ctx context.Context, in *AdminCreateUserRequest, opts ...grpc.CallOption) (*AdminCreateUserResponse, error)
	// AdminDeleteUser deletes an IAM user
	AdminDeleteUser(ctx context.Context, in *AdminDeleteUserRequest, opts ...grpc.CallOption) (*AdminDeleteUserResponse, error)
	// AdminListUsers lists all IAM users
	AdminListUsers(ctx context.Context, in *AdminListUsersRequest, opts ...grpc.CallOption) (*AdminListUsersResponse, error)
	// AdminCreateAccessKey creates a new access key for a user
	AdminCreateAccessKey(ctx context.Context, in *AdminCreateAccessKeyRequest, opts ...grpc.CallOption) (*AdminCreateAccessKeyResponse, error)
	// AdminListAccessKeys lists access keys for a user
	AdminListAccessKeys(ctx context.Context, in *AdminListAccessKeysRequest, opts ...grpc.CallOption) (*AdminListAccessKeysResponse, error)
	// AdminDeleteAccessKey deletes an access key
	AdminDeleteAccessKey(ctx context.Context, in *AdminDeleteAccessKeyRequest, opts ...grpc.CallOption) (*AdminDeleteAccessKeyResponse, error)
	// AdminListGroups lists all IAM groups
	AdminListGroups(ctx context.Context, in *AdminListGroupsRequest, opts ...grpc.CallOption) (*AdminListGroupsResponse, error)
	// AdminCreateGroup creates a new IAM group
	AdminCreateGroup(ctx context.Context, in *AdminCreateGroupRequest, opts ...grpc.CallOption) (*AdminCreateGroupResponse, error)
	// AdminDeleteGroup deletes an IAM group
	AdminDeleteGroup(ctx context.Context, in *AdminDeleteGroupRequest, opts ...grpc.CallOption) (*AdminDeleteGroupResponse, error)
	// AdminAddUserToGroup adds a user to a group
	AdminAddUserToGroup(ctx context.Context, in *AdminAddUserToGroupRequest, opts ...grpc.CallOption) (*AdminAddUserToGroupResponse, error)
	// AdminRemoveUserFromGroup removes a user from a group
	AdminRemoveUserFromGroup(ctx context.Context, in *AdminRemoveUserFromGroupRequest, opts ...grpc.CallOption) (*AdminRemoveUserFromGroupResponse, error)
	// AdminListPolicies lists all IAM policies
	AdminListPolicies(ctx context.Context, in *AdminListPoliciesRequest, opts ...grpc.CallOption) (*AdminListPoliciesResponse, error)
	// AdminCreatePolicy creates a new IAM policy
	AdminCreatePolicy(ctx context.Context, in *AdminCreatePolicyRequest, opts ...grpc.CallOption) (*AdminCreatePolicyResponse, error)
	// AdminDeletePolicy deletes an IAM policy
	AdminDeletePolicy(ctx context.Context, in *AdminDeletePolicyRequest, opts ...grpc.CallOption) (*AdminDeletePolicyResponse, error)
	// AdminAttachUserPolicy attaches a policy to a user
	AdminAttachUserPolicy(ctx context.Context, in *AdminAttachUserPolicyRequest, opts ...grpc.CallOption) (*AdminAttachUserPolicyResponse, error)
	// AdminDetachUserPolicy detaches a policy from a user
	AdminDetachUserPolicy(ctx context.Context, in *AdminDetachUserPolicyRequest, opts ...grpc.CallOption) (*AdminDetachUserPolicyResponse, error)
	// AdminAttachGroupPolicy attaches a policy to a group
	AdminAttachGroupPolicy(ctx context.Context, in *AdminAttachGroupPolicyRequest, opts ...grpc.CallOption) (*AdminAttachGroupPolicyResponse, error)
	// AdminListRoles lists all IAM roles
	AdminListRoles(ctx context.Context, in *AdminListRolesRequest, opts ...grpc.CallOption) (*AdminListRolesResponse, error)
	// AdminCreateRole creates a new IAM role
	AdminCreateRole(ctx context.Context, in *AdminCreateRoleRequest, opts ...grpc.CallOption) (*AdminCreateRoleResponse, error)
	// AdminDeleteRole deletes an IAM role
	AdminDeleteRole(ctx context.Context, in *AdminDeleteRoleRequest, opts ...grpc.CallOption) (*AdminDeleteRoleResponse, error)
	// AdminAttachRolePolicy attaches a policy to a role
	AdminAttachRolePolicy(ctx context.Context, in *AdminAttachRolePolicyRequest, opts ...grpc.CallOption) (*AdminAttachRolePolicyResponse, error)
	// AdminGetBucketPolicy gets a bucket policy
	AdminGetBucketPolicy(ctx context.Context, in *AdminGetBucketPolicyRequest, opts ...grpc.CallOption) (*AdminGetBucketPolicyResponse, error)
	// AdminPutBucketPolicy sets a bucket policy
	AdminPutBucketPolicy(ctx context.Context, in *AdminPutBucketPolicyRequest, opts ...grpc.CallOption) (*AdminPutBucketPolicyResponse, error)
	// AdminDeleteBucketPolicy deletes a bucket policy
	AdminDeleteBucketPolicy(ctx context.Context, in *AdminDeleteBucketPolicyRequest, opts ...grpc.CallOption) (*AdminDeleteBucketPolicyResponse, error)
	// AdminSimulatePolicy simulates an IAM policy evaluation
	AdminSimulatePolicy(ctx context.Context, in *AdminSimulatePolicyRequest, opts ...grpc.CallOption) (*AdminSimulatePolicyResponse, error)
}

type sTSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSTSServiceClient(cc grpc.ClientConnInterface) STSServiceClient {
	return &sTSServiceClient{cc}
}

func (c *sTSServiceClient) AssumeRole(ctx context.Context, in *AssumeRoleRequest, opts ...grpc.CallOption) (*AssumeRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssumeRoleResponse)
	err := c.cc.Invoke(ctx, STSService_AssumeRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sTSServiceClient) GetSessionToken(ctx context.Context, in *GetSessionTokenRequest, opts ...grpc.CallOption) (*GetSessionTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionTokenResponse)
	err := c.cc.Invoke(ctx, STSService_GetSessionToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sTSServiceClient) GetFederationToken(ctx context.Context, in *GetFederationTokenRequest, opts ...grpc.CallOption) (*GetFederationTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFederationTokenResponse)
	err := c.cc.Invoke(ctx, STSService_GetFederationToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sTSServiceClient) LookupUserByAccessKey(ctx context.Context, in *LookupUserByAccessKeyRequest, opts ...grpc.CallOption) (*LookupUserByAccessKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupUserByAccessKeyResponse)
	err := c.cc.Invoke(ctx, STSService_LookupUserByAccessKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sTSServiceClient) DecryptSecretKey(ctx context.Context, in *DecryptSecretKeyRequest, opts ...grpc.CallOption) (*DecryptSecretKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecryptSecretKeyResponse)
	err := c.cc.Invoke(ctx, STSService_DecryptSecretKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sTSServiceClient) LookupTempCredential(ctx context.Context, in *LookupTempCredentialRequest, opts ...grpc.CallOption) (*LookupTempCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupTempCredentialResponse)
	err := c.cc.Invoke(ctx, STSService_LookupTempCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sTSServiceClient) LookupUser(ctx context.Context, in *LookupUserRequest, opts ...grpc.CallOption) (*LookupUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupUserResponse)
	err := c.cc.Invoke(ctx, STSService_LookupUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sTSServiceClient) EvaluateAccess(ctx context.Context, in *EvaluateAccessRequest, opts ...grpc.CallOption) (*EvaluateAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateAccessResponse)
	err := c.cc.Invoke(ctx, STSService_EvaluateAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sTSServiceClient) AdminCreateUser(ctx context.Context, in *AdminCreateUserRequest, opts ...grpc.CallOption) (*AdminCreateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminCreateUserResponse)
	err := c.cc.Invoke(ctx, STSService_AdminCreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sTSServiceClient) AdminDeleteUser(ctx context.Context, in *AdminDeleteUserRequest, opts ...grpc.CallOption) (*AdminDeleteUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminDeleteUserResponse)
	err := c.cc.Invoke(ctx, STSService_AdminDeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sTSServiceClient) AdminListUsers(ctx context.Context, in *AdminListUsersRequest, opts ...grpc.CallOption) (*AdminListUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListUsersResponse)
	err := c.cc.Invoke(ctx, STSService_AdminListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sTSServiceClient) AdminCreateAccessKey(ctx context.Context, in *AdminCreateAccessKeyRequest, opts ...grpc.CallOption) (*AdminCreateAccessKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminCreateAccessKeyResponse)
	err := c.cc.Invoke(ctx, STSService_AdminCreateAccessKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sTSServiceClient) AdminListAccessKeys(ctx context.Context, in *AdminListAccessKeysRequest, opts ...grpc.CallOption) (*AdminListAccessKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListAccessKeysResponse)
	err := c.cc.Invoke(ctx, STSService_AdminListAccessKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sTSServiceClient) AdminDeleteAccessKey(ctx context.Context, in *AdminDeleteAccessKeyRequest, opts ...grpc.CallOption) (*AdminDeleteAccessKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminDeleteAccessKeyResponse)
	err := c.cc.Invoke(ctx, STSService_AdminDeleteAccessKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sTSServiceClient) AdminListGroups(ctx context.Context, in *AdminListGroupsRequest, opts ...grpc.CallOption) (*AdminListGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListGroupsResponse)
	err := c.cc.Invoke(ctx, STSService_AdminListGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sTSServiceClient) AdminCreateGroup(ctx context.Context, in *AdminCreateGroupRequest, opts ...grpc.CallOption) (*AdminCreateGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminCreateGroupResponse)
	err := c.cc.Invoke(ctx, STSService_AdminCreateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sTSServiceClient) AdminDeleteGroup(ctx context.Context, in *AdminDeleteGroupRequest, opts ...grpc.CallOption) (*AdminDeleteGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminDeleteGroupResponse)
	err := c.cc.Invoke(ctx, STSService_AdminDeleteGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sTSServiceClient) AdminAddUserToGroup(ctx context.Context, in *AdminAddUserToGroupRequest, opts ...grpc.CallOption) (*AdminAddUserToGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminAddUserToGroupResponse)
	err := c.cc.Invoke(ctx, STSService_AdminAddUserToGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sTSServiceClient) AdminRemoveUserFromGroup(ctx context.Context, in *AdminRemoveUserFromGroupRequest, opts ...grpc.CallOption) (*AdminRemoveUserFromGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminRemoveUserFromGroupResponse)
	err := c.cc.Invoke(ctx, STSService_AdminRemoveUserFromGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sTSServiceClient) AdminListPolicies(ctx context.Context, in *AdminListPoliciesRequest, opts ...grpc.CallOption) (*AdminListPoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListPoliciesResponse)
	err := c.cc.Invoke(ctx, STSService_AdminListPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sTSServiceClient) AdminCreatePolicy(ctx context.Context, in *AdminCreatePolicyRequest, opts ...grpc.CallOption) (*AdminCreatePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminCreatePolicyResponse)
	err := c.cc.Invoke(ctx, STSService_AdminCreatePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sTSServiceClient) AdminDeletePolicy(ctx context.Context, in *AdminDeletePolicyRequest, opts ...grpc.CallOption) (*AdminDeletePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminDeletePolicyResponse)
	err := c.cc.Invoke(ctx, STSService_AdminDeletePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sTSServiceClient) AdminAttachUserPolicy(ctx context.Context, in *AdminAttachUserPolicyRequest, opts ...grpc.CallOption) (*AdminAttachUserPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminAttachUserPolicyResponse)
	err := c.cc.Invoke(ctx, STSService_AdminAttachUserPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sTSServiceClient) AdminDetachUserPolicy(ctx context.Context, in *AdminDetachUserPolicyRequest, opts ...grpc.CallOption) (*AdminDetachUserPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminDetachUserPolicyResponse)
	err := c.cc.Invoke(ctx, STSService_AdminDetachUserPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sTSServiceClient) AdminAttachGroupPolicy(ctx context.Context, in *AdminAttachGroupPolicyRequest, opts ...grpc.CallOption) (*AdminAttachGroupPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminAttachGroupPolicyResponse)
	err := c.cc.Invoke(ctx, STSService_AdminAttachGroupPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sTSServiceClient) AdminListRoles(ctx context.Context, in *AdminListRolesRequest, opts ...grpc.CallOption) (*AdminListRolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListRolesResponse)
	err := c.cc.Invoke(ctx, STSService_AdminListRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sTSServiceClient) AdminCreateRole(ctx context.Context, in *AdminCreateRoleRequest, opts ...grpc.CallOption) (*AdminCreateRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminCreateRoleResponse)
	err := c.cc.Invoke(ctx, STSService_AdminCreateRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sTSServiceClient) AdminDeleteRole(ctx context.Context, in *AdminDeleteRoleRequest, opts ...grpc.CallOption) (*AdminDeleteRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminDeleteRoleResponse)
	err := c.cc.Invoke(ctx, STSService_AdminDeleteRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sTSServiceClient) AdminAttachRolePolicy(ctx context.Context, in *AdminAttachRolePolicyRequest, opts ...grpc.CallOption) (*AdminAttachRolePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminAttachRolePolicyResponse)
	err := c.cc.Invoke(ctx, STSService_AdminAttachRolePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sTSServiceClient) AdminGetBucketPolicy(ctx context.Context, in *AdminGetBucketPolicyRequest, opts ...grpc.CallOption) (*AdminGetBucketPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminGetBucketPolicyResponse)
	err := c.cc.Invoke(ctx, STSService_AdminGetBucketPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sTSServiceClient) AdminPutBucketPolicy(ctx context.Context, in *AdminPutBucketPolicyRequest, opts ...grpc.CallOption) (*AdminPutBucketPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminPutBucketPolicyResponse)
	err := c.cc.Invoke(ctx, STSService_AdminPutBucketPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sTSServiceClient) AdminDeleteBucketPolicy(ctx context.Context, in *AdminDeleteBucketPolicyRequest, opts ...grpc.CallOption) (*AdminDeleteBucketPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminDeleteBucketPolicyResponse)
	err := c.cc.Invoke(ctx, STSService_AdminDeleteBucketPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sTSServiceClient) AdminSimulatePolicy(ctx context.Context, in *AdminSimulatePolicyRequest, opts ...grpc.CallOption) (*AdminSimulatePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminSimulatePolicyResponse)
	err := c.cc.Invoke(ctx, STSService_AdminSimulatePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// STSServiceServer is the server API for STSService service.
// All implementations must embed UnimplementedSTSServiceServer
// for forward compatibility.
//
// STS Service - Security Token Service + IAM Lookup
type STSServiceServer interface {
	// AssumeRole returns temporary credentials for an assumed role
	AssumeRole(context.Context, *AssumeRoleRequest) (*AssumeRoleResponse, error)
	// GetSessionToken returns temporary credentials for the current user
	GetSessionToken(context.Context, *GetSessionTokenRequest) (*GetSessionTokenResponse, error)
	// GetFederationToken returns temporary credentials for a federated user
	GetFederationToken(context.Context, *GetFederationTokenRequest) (*GetFederationTokenResponse, error)
	// LookupUserByAccessKey finds a user by access key ID
	LookupUserByAccessKey(context.Context, *LookupUserByAccessKeyRequest) (*LookupUserByAccessKeyResponse, error)
	// DecryptSecretKey decrypts an encrypted secret key
	DecryptSecretKey(context.Context, *DecryptSecretKeyRequest) (*DecryptSecretKeyResponse, error)
	// LookupTempCredential finds a temporary credential by access key ID
	LookupTempCredential(context.Context, *LookupTempCredentialRequest) (*LookupTempCredentialResponse, error)
	// LookupUser finds a user by name
	LookupUser(context.Context, *LookupUserRequest) (*LookupUserResponse, error)
	// EvaluateAccess evaluates IAM policy for a request
	EvaluateAccess(context.Context, *EvaluateAccessRequest) (*EvaluateAccessResponse, error)
	// AdminCreateUser creates a new IAM user
	AdminCreateUser(context.Context, *AdminCreateUserRequest) (*AdminCreateUserResponse, error)
	// AdminDeleteUser deletes an IAM user
	AdminDeleteUser(context.Context, *AdminDeleteUserRequest) (*AdminDeleteUserResponse, error)
	// AdminListUsers lists all IAM users
	AdminListUsers(context.Context, *AdminListUsersRequest) (*AdminListUsersResponse, error)
	// AdminCreateAccessKey creates a new access key for a user
	AdminCreateAccessKey(context.Context, *AdminCreateAccessKeyRequest) (*AdminCreateAccessKeyResponse, error)
	// AdminListAccessKeys lists access keys for a user
	AdminListAccessKeys(context.Context, *AdminListAccessKeysRequest) (*AdminListAccessKeysResponse, error)
	// AdminDeleteAccessKey deletes an access key
	AdminDeleteAccessKey(context.Context, *AdminDeleteAccessKeyRequest) (*AdminDeleteAccessKeyResponse, error)
	// AdminListGroups lists all IAM groups
	AdminListGroups(context.Context, *AdminListGroupsRequest) (*AdminListGroupsResponse, error)
	// AdminCreateGroup creates a new IAM group
	AdminCreateGroup(context.Context, *AdminCreateGroupRequest) (*AdminCreateGroupResponse, error)
	// AdminDeleteGroup deletes an IAM group
	AdminDeleteGroup(context.Context, *AdminDeleteGroupRequest) (*AdminDeleteGroupResponse, error)
	// AdminAddUserToGroup adds a user to a group
	AdminAddUserToGroup(context.Context, *AdminAddUserToGroupRequest) (*AdminAddUserToGroupResponse, error)
	// AdminRemoveUserFromGroup removes a user from a group
	AdminRemoveUserFromGroup(context.Context, *AdminRemoveUserFromGroupRequest) (*AdminRemoveUserFromGroupResponse, error)
	// AdminListPolicies lists all IAM policies
	AdminListPolicies(context.Context, *AdminListPoliciesRequest) (*AdminListPoliciesResponse, error)
	// AdminCreatePolicy creates a new IAM policy
	AdminCreatePolicy(context.Context, *AdminCreatePolicyRequest) (*AdminCreatePolicyResponse, error)
	// AdminDeletePolicy deletes an IAM policy
	AdminDeletePolicy(context.Context, *AdminDeletePolicyRequest) (*AdminDeletePolicyResponse, error)
	// AdminAttachUserPolicy attaches a policy to a user
	AdminAttachUserPolicy(context.Context, *AdminAttachUserPolicyRequest) (*AdminAttachUserPolicyResponse, error)
	// AdminDetachUserPolicy detaches a policy from a user
	AdminDetachUserPolicy(context.Context, *AdminDetachUserPolicyRequest) (*AdminDetachUserPolicyResponse, error)
	// AdminAttachGroupPolicy attaches a policy to a group
	AdminAttachGroupPolicy(context.Context, *AdminAttachGroupPolicyRequest) (*AdminAttachGroupPolicyResponse, error)
	// AdminListRoles lists all IAM roles
	AdminListRoles(context.Context, *AdminListRolesRequest) (*AdminListRolesResponse, error)
	// AdminCreateRole creates a new IAM role
	AdminCreateRole(context.Context, *AdminCreateRoleRequest) (*AdminCreateRoleResponse, error)
	// AdminDeleteRole deletes an IAM role
	AdminDeleteRole(context.Context, *AdminDeleteRoleRequest) (*AdminDeleteRoleResponse, error)
	// AdminAttachRolePolicy attaches a policy to a role
	AdminAttachRolePolicy(context.Context, *AdminAttachRolePolicyRequest) (*AdminAttachRolePolicyResponse, error)
	// AdminGetBucketPolicy gets a bucket policy
	AdminGetBucketPolicy(context.Context, *AdminGetBucketPolicyRequest) (*AdminGetBucketPolicyResponse, error)
	// AdminPutBucketPolicy sets a bucket policy
	AdminPutBucketPolicy(context.Context, *AdminPutBucketPolicyRequest) (*AdminPutBucketPolicyResponse, error)
	// AdminDeleteBucketPolicy deletes a bucket policy
	AdminDeleteBucketPolicy(context.Context, *AdminDeleteBucketPolicyRequest) (*AdminDeleteBucketPolicyResponse, error)
	// AdminSimulatePolicy simulates an IAM policy evaluation
	AdminSimulatePolicy(context.Context, *AdminSimulatePolicyRequest) (*AdminSimulatePolicyResponse, error)
	mustEmbedUnimplementedSTSServiceServer()
}

// UnimplementedSTSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSTSServiceServer struct{}

func (UnimplementedSTSServiceServer) AssumeRole(context.Context, *AssumeRoleRequest) (*AssumeRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssumeRole not implemented")
}
func (UnimplementedSTSServiceServer) GetSessionToken(context.Context, *GetSessionTokenRequest) (*GetSessionTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSessionToken not implemented")
}
func (UnimplementedSTSServiceServer) GetFederationToken(context.Context, *GetFederationTokenRequest) (*GetFederationTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFederationToken not implemented")
}
func (UnimplementedSTSServiceServer) LookupUserByAccessKey(context.Context, *LookupUserByAccessKeyRequest) (*LookupUserByAccessKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupUserByAccessKey not implemented")
}
func (UnimplementedSTSServiceServer) DecryptSecretKey(context.Context, *DecryptSecretKeyRequest) (*DecryptSecretKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DecryptSecretKey not implemented")
}
func (UnimplementedSTSServiceServer) LookupTempCredential(context.Context, *LookupTempCredentialRequest) (*LookupTempCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupTempCredential not implemented")
}
func (UnimplementedSTSServiceServer) LookupUser(context.Context, *LookupUserRequest) (*LookupUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupUser not implemented")
}
func (UnimplementedSTSServiceServer) EvaluateAccess(context.Context, *EvaluateAccessRequest) (*EvaluateAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluateAccess not implemented")
}
func (UnimplementedSTSServiceServer) AdminCreateUser(context.Context, *AdminCreateUserRequest) (*AdminCreateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminCreateUser not implemented")
}
func (UnimplementedSTSServiceServer) AdminDeleteUser(context.Context, *AdminDeleteUserRequest) (*AdminDeleteUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminDeleteUser not implemented")
}
func (UnimplementedSTSServiceServer) AdminListUsers(context.Context, *AdminListUsersRequest) (*AdminListUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminListUsers not implemented")
}
func (UnimplementedSTSServiceServer) AdminCreateAccessKey(context.Context, *AdminCreateAccessKeyRequest) (*AdminCreateAccessKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminCreateAccessKey not implemented")
}
func (UnimplementedSTSServiceServer) AdminListAccessKeys(context.Context, *AdminListAccessKeysRequest) (*AdminListAccessKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminListAccessKeys not implemented")
}
func (UnimplementedSTSServiceServer) AdminDeleteAccessKey(context.Context, *AdminDeleteAccessKeyRequest) (*AdminDeleteAccessKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminDeleteAccessKey not implemented")
}
func (UnimplementedSTSServiceServer) AdminListGroups(context.Context, *AdminListGroupsRequest) (*AdminListGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminListGroups not implemented")
}
func (UnimplementedSTSServiceServer) AdminCreateGroup(context.Context, *AdminCreateGroupRequest) (*AdminCreateGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminCreateGroup not implemented")
}
func (UnimplementedSTSServiceServer) AdminDeleteGroup(context.Context, *AdminDeleteGroupRequest) (*AdminDeleteGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminDeleteGroup not implemented")
}
func (UnimplementedSTSServiceServer) AdminAddUserToGroup(context.Context, *AdminAddUserToGroupRequest) (*AdminAddUserToGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminAddUserToGroup not implemented")
}
func (UnimplementedSTSServiceServer) AdminRemoveUserFromGroup(context.Context, *AdminRemoveUserFromGroupRequest) (*AdminRemoveUserFromGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminRemoveUserFromGroup not implemented")
}
func (UnimplementedSTSServiceServer) AdminListPolicies(context.Context, *AdminListPoliciesRequest) (*AdminListPoliciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminListPolicies not implemented")
}
func (UnimplementedSTSServiceServer) AdminCreatePolicy(context.Context, *AdminCreatePolicyRequest) (*AdminCreatePolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminCreatePolicy not implemented")
}
func (UnimplementedSTSServiceServer) AdminDeletePolicy(context.Context, *AdminDeletePolicyRequest) (*AdminDeletePolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminDeletePolicy not implemented")
}
func (UnimplementedSTSServiceServer) AdminAttachUserPolicy(context.Context, *AdminAttachUserPolicyRequest) (*AdminAttachUserPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminAttachUserPolicy not implemented")
}
func (UnimplementedSTSServiceServer) AdminDetachUserPolicy(context.Context, *AdminDetachUserPolicyRequest) (*AdminDetachUserPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminDetachUserPolicy not implemented")
}
func (UnimplementedSTSServiceServer) AdminAttachGroupPolicy(context.Context, *AdminAttachGroupPolicyRequest) (*AdminAttachGroupPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminAttachGroupPolicy not implemented")
}
func (UnimplementedSTSServiceServer) AdminListRoles(context.Context, *AdminListRolesRequest) (*AdminListRolesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminListRoles not implemented")
}
func (UnimplementedSTSServiceServer) AdminCreateRole(context.Context, *AdminCreateRoleRequest) (*AdminCreateRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminCreateRole not implemented")
}
func (UnimplementedSTSServiceServer) AdminDeleteRole(context.Context, *AdminDeleteRoleRequest) (*AdminDeleteRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminDeleteRole not implemented")
}
func (UnimplementedSTSServiceServer) AdminAttachRolePolicy(context.Context, *AdminAttachRolePolicyRequest) (*AdminAttachRolePolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminAttachRolePolicy not implemented")
}
func (UnimplementedSTSServiceServer) AdminGetBucketPolicy(context.Context, *AdminGetBucketPolicyRequest) (*AdminGetBucketPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminGetBucketPolicy not implemented")
}
func (UnimplementedSTSServiceServer) AdminPutBucketPolicy(context.Context, *AdminPutBucketPolicyRequest) (*AdminPutBucketPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminPutBucketPolicy not implemented")
}
func (UnimplementedSTSServiceServer) AdminDeleteBucketPolicy(context.Context, *AdminDeleteBucketPolicyRequest) (*AdminDeleteBucketPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminDeleteBucketPolicy not implemented")
}
func (UnimplementedSTSServiceServer) AdminSimulatePolicy(context.Context, *AdminSimulatePolicyRequest) (*AdminSimulatePolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminSimulatePolicy not implemented")
}
func (UnimplementedSTSServiceServer) mustEmbedUnimplementedSTSServiceServer() {}
func (UnimplementedSTSServiceServer) testEmbeddedByValue()                    {}

// UnsafeSTSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to STSServiceServer will
// result in compilation errors.
type UnsafeSTSServiceServer interface {
	mustEmbedUnimplementedSTSServiceServer()
}

func RegisterSTSServiceServer(s grpc.ServiceRegistrar, srv STSServiceServer) {
	// If the following call panics, it indicates UnimplementedSTSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&STSService_ServiceDesc, srv)
}

func _STSService_AssumeRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssumeRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).AssumeRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_AssumeRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).AssumeRole(ctx, req.(*AssumeRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _STSService_GetSessionToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).GetSessionToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_GetSessionToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).GetSessionToken(ctx, req.(*GetSessionTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _STSService_GetFederationToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFederationTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).GetFederationToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_GetFederationToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).GetFederationToken(ctx, req.(*GetFederationTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _STSService_LookupUserByAccessKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupUserByAccessKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).LookupUserByAccessKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_LookupUserByAccessKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).LookupUserByAccessKey(ctx, req.(*LookupUserByAccessKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _STSService_DecryptSecretKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptSecretKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).DecryptSecretKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_DecryptSecretKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).DecryptSecretKey(ctx, req.(*DecryptSecretKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _STSService_LookupTempCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupTempCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).LookupTempCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_LookupTempCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).LookupTempCredential(ctx, req.(*LookupTempCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _STSService_LookupUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).LookupUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_LookupUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).LookupUser(ctx, req.(*LookupUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _STSService_EvaluateAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).EvaluateAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_EvaluateAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).EvaluateAccess(ctx, req.(*EvaluateAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _STSService_AdminCreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminCreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).AdminCreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_AdminCreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).AdminCreateUser(ctx, req.(*AdminCreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _STSService_AdminDeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminDeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).AdminDeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_AdminDeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).AdminDeleteUser(ctx, req.(*AdminDeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _STSService_AdminListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).AdminListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_AdminListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).AdminListUsers(ctx, req.(*AdminListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _STSService_AdminCreateAccessKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminCreateAccessKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).AdminCreateAccessKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_AdminCreateAccessKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).AdminCreateAccessKey(ctx, req.(*AdminCreateAccessKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _STSService_AdminListAccessKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListAccessKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).AdminListAccessKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_AdminListAccessKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).AdminListAccessKeys(ctx, req.(*AdminListAccessKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _STSService_AdminDeleteAccessKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminDeleteAccessKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).AdminDeleteAccessKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_AdminDeleteAccessKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).AdminDeleteAccessKey(ctx, req.(*AdminDeleteAccessKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _STSService_AdminListGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).AdminListGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_AdminListGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).AdminListGroups(ctx, req.(*AdminListGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _STSService_AdminCreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminCreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).AdminCreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_AdminCreateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).AdminCreateGroup(ctx, req.(*AdminCreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _STSService_AdminDeleteGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminDeleteGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).AdminDeleteGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_AdminDeleteGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).AdminDeleteGroup(ctx, req.(*AdminDeleteGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _STSService_AdminAddUserToGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminAddUserToGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).AdminAddUserToGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_AdminAddUserToGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).AdminAddUserToGroup(ctx, req.(*AdminAddUserToGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _STSService_AdminRemoveUserFromGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminRemoveUserFromGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).AdminRemoveUserFromGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_AdminRemoveUserFromGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).AdminRemoveUserFromGroup(ctx, req.(*AdminRemoveUserFromGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _STSService_AdminListPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).AdminListPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_AdminListPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).AdminListPolicies(ctx, req.(*AdminListPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _STSService_AdminCreatePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminCreatePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).AdminCreatePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_AdminCreatePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).AdminCreatePolicy(ctx, req.(*AdminCreatePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _STSService_AdminDeletePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminDeletePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).AdminDeletePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_AdminDeletePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).AdminDeletePolicy(ctx, req.(*AdminDeletePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _STSService_AdminAttachUserPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminAttachUserPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).AdminAttachUserPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_AdminAttachUserPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).AdminAttachUserPolicy(ctx, req.(*AdminAttachUserPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _STSService_AdminDetachUserPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminDetachUserPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).AdminDetachUserPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_AdminDetachUserPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).AdminDetachUserPolicy(ctx, req.(*AdminDetachUserPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _STSService_AdminAttachGroupPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminAttachGroupPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).AdminAttachGroupPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_AdminAttachGroupPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).AdminAttachGroupPolicy(ctx, req.(*AdminAttachGroupPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _STSService_AdminListRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).AdminListRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_AdminListRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).AdminListRoles(ctx, req.(*AdminListRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _STSService_AdminCreateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminCreateRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).AdminCreateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_AdminCreateRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).AdminCreateRole(ctx, req.(*AdminCreateRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _STSService_AdminDeleteRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminDeleteRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).AdminDeleteRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_AdminDeleteRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).AdminDeleteRole(ctx, req.(*AdminDeleteRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _STSService_AdminAttachRolePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminAttachRolePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).AdminAttachRolePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_AdminAttachRolePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).AdminAttachRolePolicy(ctx, req.(*AdminAttachRolePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _STSService_AdminGetBucketPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminGetBucketPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).AdminGetBucketPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_AdminGetBucketPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).AdminGetBucketPolicy(ctx, req.(*AdminGetBucketPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _STSService_AdminPutBucketPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminPutBucketPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).AdminPutBucketPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_AdminPutBucketPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).AdminPutBucketPolicy(ctx, req.(*AdminPutBucketPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _STSService_AdminDeleteBucketPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminDeleteBucketPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).AdminDeleteBucketPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_AdminDeleteBucketPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).AdminDeleteBucketPolicy(ctx, req.(*AdminDeleteBucketPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _STSService_AdminSimulatePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminSimulatePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).AdminSimulatePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_AdminSimulatePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).AdminSimulatePolicy(ctx, req.(*AdminSimulatePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// STSService_ServiceDesc is the grpc.ServiceDesc for STSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var STSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sts.STSService",
	HandlerType: (*STSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssumeRole",
			Handler:    _STSService_AssumeRole_Handler,
		},
		{
			MethodName: "GetSessionToken",
			Handler:    _STSService_GetSessionToken_Handler,
		},
		{
			MethodName: "GetFederationToken",
			Handler:    _STSService_GetFederationToken_Handler,
		},
		{
			MethodName: "LookupUserByAccessKey",
			Handler:    _STSService_LookupUserByAccessKey_Handler,
		},
		{
			MethodName: "DecryptSecretKey",
			Handler:    _STSService_DecryptSecretKey_Handler,
		},
		{
			MethodName: "LookupTempCredential",
			Handler:    _STSService_LookupTempCredential_Handler,
		},
		{
			MethodName: "LookupUser",
			Handler:    _STSService_LookupUser_Handler,
		},
		{
			MethodName: "EvaluateAccess",
			Handler:    _STSService_EvaluateAccess_Handler,
		},
		{
			MethodName: "AdminCreateUser",
			Handler:    _STSService_AdminCreateUser_Handler,
		},
		{
			MethodName: "AdminDeleteUser",
			Handler:    _STSService_AdminDeleteUser_Handler,
		},
		{
			MethodName: "AdminListUsers",
			Handler:    _STSService_AdminListUsers_Handler,
		},
		{
			MethodName: "AdminCreateAccessKey",
			Handler:    _STSService_AdminCreateAccessKey_Handler,
		},
		{
			MethodName: "AdminListAccessKeys",
			Handler:    _STSService_AdminListAccessKeys_Handler,
		},
		{
			MethodName: "AdminDeleteAccessKey",
			Handler:    _STSService_AdminDeleteAccessKey_Handler,
		},
		{
			MethodName: "AdminListGroups",
			Handler:    _STSService_AdminListGroups_Handler,
		},
		{
			MethodName: "AdminCreateGroup",
			Handler:    _STSService_AdminCreateGroup_Handler,
		},
		{
			MethodName: "AdminDeleteGroup",
			Handler:    _STSService_AdminDeleteGroup_Handler,
		},
		{
			MethodName: "AdminAddUserToGroup",
			Handler:    _STSService_AdminAddUserToGroup_Handler,
		},
		{
			MethodName: "AdminRemoveUserFromGroup",
			Handler:    _STSService_AdminRemoveUserFromGroup_Handler,
		},
		{
			MethodName: "AdminListPolicies",
			Handler:    _STSService_AdminListPolicies_Handler,
		},
		{
			MethodName: "AdminCreatePolicy",
			Handler:    _STSService_AdminCreatePolicy_Handler,
		},
		{
			MethodName: "AdminDeletePolicy",
			Handler:    _STSService_AdminDeletePolicy_Handler,
		},
		{
			MethodName: "AdminAttachUserPolicy",
			Handler:    _STSService_AdminAttachUserPolicy_Handler,
		},
		{
			MethodName: "AdminDetachUserPolicy",
			Handler:    _STSService_AdminDetachUserPolicy_Handler,
		},
		{
			MethodName: "AdminAttachGroupPolicy",
			Handler:    _STSService_AdminAttachGroupPolicy_Handler,
		},
		{
			MethodName: "AdminListRoles",
			Handler:    _STSService_AdminListRoles_Handler,
		},
		{
			MethodName: "AdminCreateRole",
			Handler:    _STSService_AdminCreateRole_Handler,
		},
		{
			MethodName: "AdminDeleteRole",
			Handler:    _STSService_AdminDeleteRole_Handler,
		},
		{
			MethodName: "AdminAttachRolePolicy",
			Handler:    _STSService_AdminAttachRolePolicy_Handler,
		},
		{
			MethodName: "AdminGetBucketPolicy",
			Handler:    _STSService_AdminGetBucketPolicy_Handler,
		},
		{
			MethodName: "AdminPutBucketPolicy",
			Handler:    _STSService_AdminPutBucketPolicy_Handler,
		},
		{
			MethodName: "AdminDeleteBucketPolicy",
			Handler:    _STSService_AdminDeleteBucketPolicy_Handler,
		},
		{
			MethodName: "AdminSimulatePolicy",
			Handler:    _STSService_AdminSimulatePolicy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sts.proto",
}
