run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asciicheck
    - bodyclose
    - contextcheck
    - copyloopvar
    - decorder
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - forcetypeassert
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - godot
    - gofmt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - intrange
    - loggercheck
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - stylecheck
    - tenv
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    enable:
      - shadow
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
  goimports:
    local-prefixes: cipherlake
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - path: proto/
      linters:
        - all
