FROM alpine:3.20

RUN apk add --no-cache ca-certificates wget && \
    addgroup -g 1000 -S cipherlake && \
    adduser -u 1000 -S cipherlake -G cipherlake

WORKDIR /home/cipherlake

COPY cipherlake-linux /usr/local/bin/cipherlake
COPY cipherlakectl-linux /usr/local/bin/cipherlakectl
COPY config.yaml /etc/cipherlake/config.yaml

RUN chmod +x /usr/local/bin/cipherlake /usr/local/bin/cipherlakectl && \
    mkdir -p /var/lib/cipherlake/data /var/lib/cipherlake/metadata /var/lib/cipherlake/keystore /etc/cipherlake && \
    chown -R cipherlake:cipherlake /var/lib/cipherlake /etc/cipherlake

USER cipherlake

EXPOSE 8080

VOLUME ["/var/lib/cipherlake", "/etc/cipherlake"]

ENTRYPOINT ["/usr/local/bin/cipherlake"]
CMD ["--config", "/etc/cipherlake/config.yaml"]
