// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: token.proto

package token

import (
	common "cipherlake/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IssueWriteTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,3,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,4,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"` // Token lifetime, default 30s if 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueWriteTokenRequest) Reset() {
	*x = IssueWriteTokenRequest{}
	mi := &file_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueWriteTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueWriteTokenRequest) ProtoMessage() {}

func (x *IssueWriteTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueWriteTokenRequest.ProtoReflect.Descriptor instead.
func (*IssueWriteTokenRequest) Descriptor() ([]byte, []int) {
	return file_token_proto_rawDescGZIP(), []int{0}
}

func (x *IssueWriteTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IssueWriteTokenRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *IssueWriteTokenRequest) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *IssueWriteTokenRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type IssueWriteTokenResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Token         *common.DelegationToken `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Error         *common.Error           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueWriteTokenResponse) Reset() {
	*x = IssueWriteTokenResponse{}
	mi := &file_token_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueWriteTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueWriteTokenResponse) ProtoMessage() {}

func (x *IssueWriteTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_token_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueWriteTokenResponse.ProtoReflect.Descriptor instead.
func (*IssueWriteTokenResponse) Descriptor() ([]byte, []int) {
	return file_token_proto_rawDescGZIP(), []int{1}
}

func (x *IssueWriteTokenResponse) GetToken() *common.DelegationToken {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *IssueWriteTokenResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type IssueReadTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,3,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	ContentHash   string                 `protobuf:"bytes,4,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"` // For integrity verification
	TtlSeconds    int64                  `protobuf:"varint,5,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueReadTokenRequest) Reset() {
	*x = IssueReadTokenRequest{}
	mi := &file_token_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueReadTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueReadTokenRequest) ProtoMessage() {}

func (x *IssueReadTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_token_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueReadTokenRequest.ProtoReflect.Descriptor instead.
func (*IssueReadTokenRequest) Descriptor() ([]byte, []int) {
	return file_token_proto_rawDescGZIP(), []int{2}
}

func (x *IssueReadTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IssueReadTokenRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *IssueReadTokenRequest) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *IssueReadTokenRequest) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *IssueReadTokenRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type IssueReadTokenResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Token         *common.DelegationToken `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Error         *common.Error           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueReadTokenResponse) Reset() {
	*x = IssueReadTokenResponse{}
	mi := &file_token_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueReadTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueReadTokenResponse) ProtoMessage() {}

func (x *IssueReadTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_token_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueReadTokenResponse.ProtoReflect.Descriptor instead.
func (*IssueReadTokenResponse) Descriptor() ([]byte, []int) {
	return file_token_proto_rawDescGZIP(), []int{3}
}

func (x *IssueReadTokenResponse) GetToken() *common.DelegationToken {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *IssueReadTokenResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type IssueDeleteTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,3,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,4,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueDeleteTokenRequest) Reset() {
	*x = IssueDeleteTokenRequest{}
	mi := &file_token_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueDeleteTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueDeleteTokenRequest) ProtoMessage() {}

func (x *IssueDeleteTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_token_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueDeleteTokenRequest.ProtoReflect.Descriptor instead.
func (*IssueDeleteTokenRequest) Descriptor() ([]byte, []int) {
	return file_token_proto_rawDescGZIP(), []int{4}
}

func (x *IssueDeleteTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IssueDeleteTokenRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *IssueDeleteTokenRequest) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *IssueDeleteTokenRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type IssueDeleteTokenResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Token         *common.DelegationToken `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Error         *common.Error           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueDeleteTokenResponse) Reset() {
	*x = IssueDeleteTokenResponse{}
	mi := &file_token_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueDeleteTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueDeleteTokenResponse) ProtoMessage() {}

func (x *IssueDeleteTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_token_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueDeleteTokenResponse.ProtoReflect.Descriptor instead.
func (*IssueDeleteTokenResponse) Descriptor() ([]byte, []int) {
	return file_token_proto_rawDescGZIP(), []int{5}
}

func (x *IssueDeleteTokenResponse) GetToken() *common.DelegationToken {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *IssueDeleteTokenResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type ValidateTokenRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Token         *common.DelegationToken `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpectedType  common.TokenType        `protobuf:"varint,2,opt,name=expected_type,json=expectedType,proto3,enum=cipherlake.common.TokenType" json:"expected_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_token_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_token_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_token_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateTokenRequest) GetToken() *common.DelegationToken {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *ValidateTokenRequest) GetExpectedType() common.TokenType {
	if x != nil {
		return x.ExpectedType
	}
	return common.TokenType(0)
}

type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Bucket        string                 `protobuf:"bytes,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,4,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	Error         *common.Error          `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_token_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_token_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_token_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateTokenResponse) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *ValidateTokenResponse) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *ValidateTokenResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetPublicKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicKeyRequest) Reset() {
	*x = GetPublicKeyRequest{}
	mi := &file_token_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeyRequest) ProtoMessage() {}

func (x *GetPublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_token_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeyRequest.ProtoReflect.Descriptor instead.
func (*GetPublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_token_proto_rawDescGZIP(), []int{8}
}

type GetPublicKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // Ed25519 public key
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Error         *common.Error          `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicKeyResponse) Reset() {
	*x = GetPublicKeyResponse{}
	mi := &file_token_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeyResponse) ProtoMessage() {}

func (x *GetPublicKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_token_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeyResponse.ProtoReflect.Descriptor instead.
func (*GetPublicKeyResponse) Descriptor() ([]byte, []int) {
	return file_token_proto_rawDescGZIP(), []int{9}
}

func (x *GetPublicKeyResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *GetPublicKeyResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *GetPublicKeyResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_token_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_token_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_token_proto_rawDescGZIP(), []int{10}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_token_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_token_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_token_proto_rawDescGZIP(), []int{11}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

var File_token_proto protoreflect.FileDescriptor

const file_token_proto_rawDesc = "" +
	"\n" +
	"\vtoken.proto\x12\x10cipherlake.token\x1a\x17cipherlake/common.proto\"\x89\x01\n" +
	"\x16IssueWriteTokenRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x1d\n" +
	"\n" +
	"object_key\x18\x03 \x01(\tR\tobjectKey\x12\x1f\n" +
	"\vttl_seconds\x18\x04 \x01(\x03R\n" +
	"ttlSeconds\"\x83\x01\n" +
	"\x17IssueWriteTokenResponse\x128\n" +
	"\x05token\x18\x01 \x01(\v2\".cipherlake.common.DelegationTokenR\x05token\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x18.cipherlake.common.ErrorR\x05error\"\xab\x01\n" +
	"\x15IssueReadTokenRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x1d\n" +
	"\n" +
	"object_key\x18\x03 \x01(\tR\tobjectKey\x12!\n" +
	"\fcontent_hash\x18\x04 \x01(\tR\vcontentHash\x12\x1f\n" +
	"\vttl_seconds\x18\x05 \x01(\x03R\n" +
	"ttlSeconds\"\x82\x01\n" +
	"\x16IssueReadTokenResponse\x128\n" +
	"\x05token\x18\x01 \x01(\v2\".cipherlake.common.DelegationTokenR\x05token\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x18.cipherlake.common.ErrorR\x05error\"\x8a\x01\n" +
	"\x17IssueDeleteTokenRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x1d\n" +
	"\n" +
	"object_key\x18\x03 \x01(\tR\tobjectKey\x12\x1f\n" +
	"\vttl_seconds\x18\x04 \x01(\x03R\n" +
	"ttlSeconds\"\x84\x01\n" +
	"\x18IssueDeleteTokenResponse\x128\n" +
	"\x05token\x18\x01 \x01(\v2\".cipherlake.common.DelegationTokenR\x05token\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x18.cipherlake.common.ErrorR\x05error\"\x93\x01\n" +
	"\x14ValidateTokenRequest\x128\n" +
	"\x05token\x18\x01 \x01(\v2\".cipherlake.common.DelegationTokenR\x05token\x12A\n" +
	"\rexpected_type\x18\x02 \x01(\x0e2\x1c.cipherlake.common.TokenTypeR\fexpectedType\"\xad\x01\n" +
	"\x15ValidateTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06bucket\x18\x03 \x01(\tR\x06bucket\x12\x1d\n" +
	"\n" +
	"object_key\x18\x04 \x01(\tR\tobjectKey\x12.\n" +
	"\x05error\x18\x05 \x01(\v2\x18.cipherlake.common.ErrorR\x05error\"\x15\n" +
	"\x13GetPublicKeyRequest\"|\n" +
	"\x14GetPublicKeyResponse\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12.\n" +
	"\x05error\x18\x03 \x01(\v2\x18.cipherlake.common.ErrorR\x05error\"\x0f\n" +
	"\rHealthRequest\"\x8e\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds2\xd4\x04\n" +
	"\fTokenService\x12f\n" +
	"\x0fIssueWriteToken\x12(.cipherlake.token.IssueWriteTokenRequest\x1a).cipherlake.token.IssueWriteTokenResponse\x12c\n" +
	"\x0eIssueReadToken\x12'.cipherlake.token.IssueReadTokenRequest\x1a(.cipherlake.token.IssueReadTokenResponse\x12i\n" +
	"\x10IssueDeleteToken\x12).cipherlake.token.IssueDeleteTokenRequest\x1a*.cipherlake.token.IssueDeleteTokenResponse\x12`\n" +
	"\rValidateToken\x12&.cipherlake.token.ValidateTokenRequest\x1a'.cipherlake.token.ValidateTokenResponse\x12]\n" +
	"\fGetPublicKey\x12%.cipherlake.token.GetPublicKeyRequest\x1a&.cipherlake.token.GetPublicKeyResponse\x12K\n" +
	"\x06Health\x12\x1f.cipherlake.token.HealthRequest\x1a .cipherlake.token.HealthResponseB\x18Z\x16cipherlake/proto/tokenb\x06proto3"

var (
	file_token_proto_rawDescOnce sync.Once
	file_token_proto_rawDescData []byte
)

func file_token_proto_rawDescGZIP() []byte {
	file_token_proto_rawDescOnce.Do(func() {
		file_token_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_token_proto_rawDesc), len(file_token_proto_rawDesc)))
	})
	return file_token_proto_rawDescData
}

var file_token_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_token_proto_goTypes = []any{
	(*IssueWriteTokenRequest)(nil),   // 0: cipherlake.token.IssueWriteTokenRequest
	(*IssueWriteTokenResponse)(nil),  // 1: cipherlake.token.IssueWriteTokenResponse
	(*IssueReadTokenRequest)(nil),    // 2: cipherlake.token.IssueReadTokenRequest
	(*IssueReadTokenResponse)(nil),   // 3: cipherlake.token.IssueReadTokenResponse
	(*IssueDeleteTokenRequest)(nil),  // 4: cipherlake.token.IssueDeleteTokenRequest
	(*IssueDeleteTokenResponse)(nil), // 5: cipherlake.token.IssueDeleteTokenResponse
	(*ValidateTokenRequest)(nil),     // 6: cipherlake.token.ValidateTokenRequest
	(*ValidateTokenResponse)(nil),    // 7: cipherlake.token.ValidateTokenResponse
	(*GetPublicKeyRequest)(nil),      // 8: cipherlake.token.GetPublicKeyRequest
	(*GetPublicKeyResponse)(nil),     // 9: cipherlake.token.GetPublicKeyResponse
	(*HealthRequest)(nil),            // 10: cipherlake.token.HealthRequest
	(*HealthResponse)(nil),           // 11: cipherlake.token.HealthResponse
	(*common.DelegationToken)(nil),   // 12: cipherlake.common.DelegationToken
	(*common.Error)(nil),             // 13: cipherlake.common.Error
	(common.TokenType)(0),            // 14: cipherlake.common.TokenType
}
var file_token_proto_depIdxs = []int32{
	12, // 0: cipherlake.token.IssueWriteTokenResponse.token:type_name -> cipherlake.common.DelegationToken
	13, // 1: cipherlake.token.IssueWriteTokenResponse.error:type_name -> cipherlake.common.Error
	12, // 2: cipherlake.token.IssueReadTokenResponse.token:type_name -> cipherlake.common.DelegationToken
	13, // 3: cipherlake.token.IssueReadTokenResponse.error:type_name -> cipherlake.common.Error
	12, // 4: cipherlake.token.IssueDeleteTokenResponse.token:type_name -> cipherlake.common.DelegationToken
	13, // 5: cipherlake.token.IssueDeleteTokenResponse.error:type_name -> cipherlake.common.Error
	12, // 6: cipherlake.token.ValidateTokenRequest.token:type_name -> cipherlake.common.DelegationToken
	14, // 7: cipherlake.token.ValidateTokenRequest.expected_type:type_name -> cipherlake.common.TokenType
	13, // 8: cipherlake.token.ValidateTokenResponse.error:type_name -> cipherlake.common.Error
	13, // 9: cipherlake.token.GetPublicKeyResponse.error:type_name -> cipherlake.common.Error
	0,  // 10: cipherlake.token.TokenService.IssueWriteToken:input_type -> cipherlake.token.IssueWriteTokenRequest
	2,  // 11: cipherlake.token.TokenService.IssueReadToken:input_type -> cipherlake.token.IssueReadTokenRequest
	4,  // 12: cipherlake.token.TokenService.IssueDeleteToken:input_type -> cipherlake.token.IssueDeleteTokenRequest
	6,  // 13: cipherlake.token.TokenService.ValidateToken:input_type -> cipherlake.token.ValidateTokenRequest
	8,  // 14: cipherlake.token.TokenService.GetPublicKey:input_type -> cipherlake.token.GetPublicKeyRequest
	10, // 15: cipherlake.token.TokenService.Health:input_type -> cipherlake.token.HealthRequest
	1,  // 16: cipherlake.token.TokenService.IssueWriteToken:output_type -> cipherlake.token.IssueWriteTokenResponse
	3,  // 17: cipherlake.token.TokenService.IssueReadToken:output_type -> cipherlake.token.IssueReadTokenResponse
	5,  // 18: cipherlake.token.TokenService.IssueDeleteToken:output_type -> cipherlake.token.IssueDeleteTokenResponse
	7,  // 19: cipherlake.token.TokenService.ValidateToken:output_type -> cipherlake.token.ValidateTokenResponse
	9,  // 20: cipherlake.token.TokenService.GetPublicKey:output_type -> cipherlake.token.GetPublicKeyResponse
	11, // 21: cipherlake.token.TokenService.Health:output_type -> cipherlake.token.HealthResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_token_proto_init() }
func file_token_proto_init() {
	if File_token_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_token_proto_rawDesc), len(file_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_token_proto_goTypes,
		DependencyIndexes: file_token_proto_depIdxs,
		MessageInfos:      file_token_proto_msgTypes,
	}.Build()
	File_token_proto = out.File
	file_token_proto_goTypes = nil
	file_token_proto_depIdxs = nil
}
