// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.2
// source: proto/plugin/admin.proto

package plugin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginAdminService_InstallPlugin_FullMethodName     = "/cipherlake.plugin.PluginAdminService/InstallPlugin"
	PluginAdminService_UninstallPlugin_FullMethodName   = "/cipherlake.plugin.PluginAdminService/UninstallPlugin"
	PluginAdminService_ReloadPlugin_FullMethodName      = "/cipherlake.plugin.PluginAdminService/ReloadPlugin"
	PluginAdminService_ListPlugins_FullMethodName       = "/cipherlake.plugin.PluginAdminService/ListPlugins"
	PluginAdminService_GetPluginState_FullMethodName    = "/cipherlake.plugin.PluginAdminService/GetPluginState"
	PluginAdminService_DumpPluginState_FullMethodName   = "/cipherlake.plugin.PluginAdminService/DumpPluginState"
	PluginAdminService_GetPluginLogs_FullMethodName     = "/cipherlake.plugin.PluginAdminService/GetPluginLogs"
	PluginAdminService_GetPluginMetrics_FullMethodName  = "/cipherlake.plugin.PluginAdminService/GetPluginMetrics"
	PluginAdminService_SetPluginLogLevel_FullMethodName = "/cipherlake.plugin.PluginAdminService/SetPluginLogLevel"
	PluginAdminService_AddTrustedKey_FullMethodName     = "/cipherlake.plugin.PluginAdminService/AddTrustedKey"
	PluginAdminService_RemoveTrustedKey_FullMethodName  = "/cipherlake.plugin.PluginAdminService/RemoveTrustedKey"
	PluginAdminService_ListTrustedKeys_FullMethodName   = "/cipherlake.plugin.PluginAdminService/ListTrustedKeys"
)

// PluginAdminServiceClient is the client API for PluginAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PluginAdminService is the administrative API of the plugin-loader
// microservice (spec §3.11, P3-1). It is exposed on the same gRPC server as
// PluginLoaderService but uses a separate service so Gateway traffic and
// operator traffic can be authorized independently.
type PluginAdminServiceClient interface {
	// InstallPlugin loads a plugin into the loader. The plugin may be supplied
	// as raw bytes (manifest + wasm) or as an OCI URL (P3-3).
	InstallPlugin(ctx context.Context, in *InstallPluginRequest, opts ...grpc.CallOption) (*InstallPluginResponse, error)
	// UninstallPlugin removes a plugin and frees its runtime resources.
	// Dependent plugins block uninstall unless force=true.
	UninstallPlugin(ctx context.Context, in *UninstallPluginRequest, opts ...grpc.CallOption) (*UninstallPluginResponse, error)
	// ReloadPlugin uninstalls and reinstalls a plugin from its persisted
	// registry record. Useful for picking up a changed trusted_keys tier or
	// for recovery after a partial install.
	ReloadPlugin(ctx context.Context, in *ReloadPluginRequest, opts ...grpc.CallOption) (*ReloadPluginResponse, error)
	// ListPlugins returns the installed plugins.
	ListPlugins(ctx context.Context, in *ListPluginsRequest, opts ...grpc.CallOption) (*ListPluginsResponse, error)
	// GetPluginState reads a single key from a plugin's state:kv namespace.
	GetPluginState(ctx context.Context, in *GetPluginStateRequest, opts ...grpc.CallOption) (*GetPluginStateResponse, error)
	// DumpPluginState exports the entire state:kv namespace of a plugin.
	DumpPluginState(ctx context.Context, in *DumpPluginStateRequest, opts ...grpc.CallOption) (*DumpPluginStateResponse, error)
	// GetPluginLogs returns recent log entries emitted by a plugin.
	GetPluginLogs(ctx context.Context, in *GetPluginLogsRequest, opts ...grpc.CallOption) (*GetPluginLogsResponse, error)
	// GetPluginMetrics returns recent metric samples recorded by a plugin.
	GetPluginMetrics(ctx context.Context, in *GetPluginMetricsRequest, opts ...grpc.CallOption) (*GetPluginMetricsResponse, error)
	// SetPluginLogLevel adjusts the per-plugin log level dynamically.
	SetPluginLogLevel(ctx context.Context, in *SetPluginLogLevelRequest, opts ...grpc.CallOption) (*SetPluginLogLevelResponse, error)
	// AddTrustedKey registers a new Ed25519 public key in the loader's
	// trust store. The change is replicated through Raft and persisted back
	// to config/trusted_keys.json on the leader.
	AddTrustedKey(ctx context.Context, in *AddTrustedKeyRequest, opts ...grpc.CallOption) (*AddTrustedKeyResponse, error)
	// RemoveTrustedKey deletes a trusted key by key_id. The change is
	// replicated through Raft and persisted back to config/trusted_keys.json.
	RemoveTrustedKey(ctx context.Context, in *RemoveTrustedKeyRequest, opts ...grpc.CallOption) (*RemoveTrustedKeyResponse, error)
	// ListTrustedKeys returns the current trusted keys mirror.
	ListTrustedKeys(ctx context.Context, in *ListTrustedKeysRequest, opts ...grpc.CallOption) (*ListTrustedKeysResponse, error)
}

type pluginAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginAdminServiceClient(cc grpc.ClientConnInterface) PluginAdminServiceClient {
	return &pluginAdminServiceClient{cc}
}

func (c *pluginAdminServiceClient) InstallPlugin(ctx context.Context, in *InstallPluginRequest, opts ...grpc.CallOption) (*InstallPluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallPluginResponse)
	err := c.cc.Invoke(ctx, PluginAdminService_InstallPlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginAdminServiceClient) UninstallPlugin(ctx context.Context, in *UninstallPluginRequest, opts ...grpc.CallOption) (*UninstallPluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UninstallPluginResponse)
	err := c.cc.Invoke(ctx, PluginAdminService_UninstallPlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginAdminServiceClient) ReloadPlugin(ctx context.Context, in *ReloadPluginRequest, opts ...grpc.CallOption) (*ReloadPluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadPluginResponse)
	err := c.cc.Invoke(ctx, PluginAdminService_ReloadPlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginAdminServiceClient) ListPlugins(ctx context.Context, in *ListPluginsRequest, opts ...grpc.CallOption) (*ListPluginsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPluginsResponse)
	err := c.cc.Invoke(ctx, PluginAdminService_ListPlugins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginAdminServiceClient) GetPluginState(ctx context.Context, in *GetPluginStateRequest, opts ...grpc.CallOption) (*GetPluginStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPluginStateResponse)
	err := c.cc.Invoke(ctx, PluginAdminService_GetPluginState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginAdminServiceClient) DumpPluginState(ctx context.Context, in *DumpPluginStateRequest, opts ...grpc.CallOption) (*DumpPluginStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DumpPluginStateResponse)
	err := c.cc.Invoke(ctx, PluginAdminService_DumpPluginState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginAdminServiceClient) GetPluginLogs(ctx context.Context, in *GetPluginLogsRequest, opts ...grpc.CallOption) (*GetPluginLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPluginLogsResponse)
	err := c.cc.Invoke(ctx, PluginAdminService_GetPluginLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginAdminServiceClient) GetPluginMetrics(ctx context.Context, in *GetPluginMetricsRequest, opts ...grpc.CallOption) (*GetPluginMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPluginMetricsResponse)
	err := c.cc.Invoke(ctx, PluginAdminService_GetPluginMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginAdminServiceClient) SetPluginLogLevel(ctx context.Context, in *SetPluginLogLevelRequest, opts ...grpc.CallOption) (*SetPluginLogLevelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPluginLogLevelResponse)
	err := c.cc.Invoke(ctx, PluginAdminService_SetPluginLogLevel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginAdminServiceClient) AddTrustedKey(ctx context.Context, in *AddTrustedKeyRequest, opts ...grpc.CallOption) (*AddTrustedKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddTrustedKeyResponse)
	err := c.cc.Invoke(ctx, PluginAdminService_AddTrustedKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginAdminServiceClient) RemoveTrustedKey(ctx context.Context, in *RemoveTrustedKeyRequest, opts ...grpc.CallOption) (*RemoveTrustedKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveTrustedKeyResponse)
	err := c.cc.Invoke(ctx, PluginAdminService_RemoveTrustedKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginAdminServiceClient) ListTrustedKeys(ctx context.Context, in *ListTrustedKeysRequest, opts ...grpc.CallOption) (*ListTrustedKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTrustedKeysResponse)
	err := c.cc.Invoke(ctx, PluginAdminService_ListTrustedKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginAdminServiceServer is the server API for PluginAdminService service.
// All implementations must embed UnimplementedPluginAdminServiceServer
// for forward compatibility.
//
// PluginAdminService is the administrative API of the plugin-loader
// microservice (spec §3.11, P3-1). It is exposed on the same gRPC server as
// PluginLoaderService but uses a separate service so Gateway traffic and
// operator traffic can be authorized independently.
type PluginAdminServiceServer interface {
	// InstallPlugin loads a plugin into the loader. The plugin may be supplied
	// as raw bytes (manifest + wasm) or as an OCI URL (P3-3).
	InstallPlugin(context.Context, *InstallPluginRequest) (*InstallPluginResponse, error)
	// UninstallPlugin removes a plugin and frees its runtime resources.
	// Dependent plugins block uninstall unless force=true.
	UninstallPlugin(context.Context, *UninstallPluginRequest) (*UninstallPluginResponse, error)
	// ReloadPlugin uninstalls and reinstalls a plugin from its persisted
	// registry record. Useful for picking up a changed trusted_keys tier or
	// for recovery after a partial install.
	ReloadPlugin(context.Context, *ReloadPluginRequest) (*ReloadPluginResponse, error)
	// ListPlugins returns the installed plugins.
	ListPlugins(context.Context, *ListPluginsRequest) (*ListPluginsResponse, error)
	// GetPluginState reads a single key from a plugin's state:kv namespace.
	GetPluginState(context.Context, *GetPluginStateRequest) (*GetPluginStateResponse, error)
	// DumpPluginState exports the entire state:kv namespace of a plugin.
	DumpPluginState(context.Context, *DumpPluginStateRequest) (*DumpPluginStateResponse, error)
	// GetPluginLogs returns recent log entries emitted by a plugin.
	GetPluginLogs(context.Context, *GetPluginLogsRequest) (*GetPluginLogsResponse, error)
	// GetPluginMetrics returns recent metric samples recorded by a plugin.
	GetPluginMetrics(context.Context, *GetPluginMetricsRequest) (*GetPluginMetricsResponse, error)
	// SetPluginLogLevel adjusts the per-plugin log level dynamically.
	SetPluginLogLevel(context.Context, *SetPluginLogLevelRequest) (*SetPluginLogLevelResponse, error)
	// AddTrustedKey registers a new Ed25519 public key in the loader's
	// trust store. The change is replicated through Raft and persisted back
	// to config/trusted_keys.json on the leader.
	AddTrustedKey(context.Context, *AddTrustedKeyRequest) (*AddTrustedKeyResponse, error)
	// RemoveTrustedKey deletes a trusted key by key_id. The change is
	// replicated through Raft and persisted back to config/trusted_keys.json.
	RemoveTrustedKey(context.Context, *RemoveTrustedKeyRequest) (*RemoveTrustedKeyResponse, error)
	// ListTrustedKeys returns the current trusted keys mirror.
	ListTrustedKeys(context.Context, *ListTrustedKeysRequest) (*ListTrustedKeysResponse, error)
	mustEmbedUnimplementedPluginAdminServiceServer()
}

// UnimplementedPluginAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginAdminServiceServer struct{}

func (UnimplementedPluginAdminServiceServer) InstallPlugin(context.Context, *InstallPluginRequest) (*InstallPluginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InstallPlugin not implemented")
}
func (UnimplementedPluginAdminServiceServer) UninstallPlugin(context.Context, *UninstallPluginRequest) (*UninstallPluginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UninstallPlugin not implemented")
}
func (UnimplementedPluginAdminServiceServer) ReloadPlugin(context.Context, *ReloadPluginRequest) (*ReloadPluginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReloadPlugin not implemented")
}
func (UnimplementedPluginAdminServiceServer) ListPlugins(context.Context, *ListPluginsRequest) (*ListPluginsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlugins not implemented")
}
func (UnimplementedPluginAdminServiceServer) GetPluginState(context.Context, *GetPluginStateRequest) (*GetPluginStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPluginState not implemented")
}
func (UnimplementedPluginAdminServiceServer) DumpPluginState(context.Context, *DumpPluginStateRequest) (*DumpPluginStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DumpPluginState not implemented")
}
func (UnimplementedPluginAdminServiceServer) GetPluginLogs(context.Context, *GetPluginLogsRequest) (*GetPluginLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPluginLogs not implemented")
}
func (UnimplementedPluginAdminServiceServer) GetPluginMetrics(context.Context, *GetPluginMetricsRequest) (*GetPluginMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPluginMetrics not implemented")
}
func (UnimplementedPluginAdminServiceServer) SetPluginLogLevel(context.Context, *SetPluginLogLevelRequest) (*SetPluginLogLevelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPluginLogLevel not implemented")
}
func (UnimplementedPluginAdminServiceServer) AddTrustedKey(context.Context, *AddTrustedKeyRequest) (*AddTrustedKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTrustedKey not implemented")
}
func (UnimplementedPluginAdminServiceServer) RemoveTrustedKey(context.Context, *RemoveTrustedKeyRequest) (*RemoveTrustedKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveTrustedKey not implemented")
}
func (UnimplementedPluginAdminServiceServer) ListTrustedKeys(context.Context, *ListTrustedKeysRequest) (*ListTrustedKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTrustedKeys not implemented")
}
func (UnimplementedPluginAdminServiceServer) mustEmbedUnimplementedPluginAdminServiceServer() {}
func (UnimplementedPluginAdminServiceServer) testEmbeddedByValue()                            {}

// UnsafePluginAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginAdminServiceServer will
// result in compilation errors.
type UnsafePluginAdminServiceServer interface {
	mustEmbedUnimplementedPluginAdminServiceServer()
}

func RegisterPluginAdminServiceServer(s grpc.ServiceRegistrar, srv PluginAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedPluginAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginAdminService_ServiceDesc, srv)
}

func _PluginAdminService_InstallPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginAdminServiceServer).InstallPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginAdminService_InstallPlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginAdminServiceServer).InstallPlugin(ctx, req.(*InstallPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginAdminService_UninstallPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UninstallPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginAdminServiceServer).UninstallPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginAdminService_UninstallPlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginAdminServiceServer).UninstallPlugin(ctx, req.(*UninstallPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginAdminService_ReloadPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginAdminServiceServer).ReloadPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginAdminService_ReloadPlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginAdminServiceServer).ReloadPlugin(ctx, req.(*ReloadPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginAdminService_ListPlugins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPluginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginAdminServiceServer).ListPlugins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginAdminService_ListPlugins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginAdminServiceServer).ListPlugins(ctx, req.(*ListPluginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginAdminService_GetPluginState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPluginStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginAdminServiceServer).GetPluginState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginAdminService_GetPluginState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginAdminServiceServer).GetPluginState(ctx, req.(*GetPluginStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginAdminService_DumpPluginState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DumpPluginStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginAdminServiceServer).DumpPluginState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginAdminService_DumpPluginState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginAdminServiceServer).DumpPluginState(ctx, req.(*DumpPluginStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginAdminService_GetPluginLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPluginLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginAdminServiceServer).GetPluginLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginAdminService_GetPluginLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginAdminServiceServer).GetPluginLogs(ctx, req.(*GetPluginLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginAdminService_GetPluginMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPluginMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginAdminServiceServer).GetPluginMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginAdminService_GetPluginMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginAdminServiceServer).GetPluginMetrics(ctx, req.(*GetPluginMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginAdminService_SetPluginLogLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPluginLogLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginAdminServiceServer).SetPluginLogLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginAdminService_SetPluginLogLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginAdminServiceServer).SetPluginLogLevel(ctx, req.(*SetPluginLogLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginAdminService_AddTrustedKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTrustedKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginAdminServiceServer).AddTrustedKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginAdminService_AddTrustedKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginAdminServiceServer).AddTrustedKey(ctx, req.(*AddTrustedKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginAdminService_RemoveTrustedKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTrustedKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginAdminServiceServer).RemoveTrustedKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginAdminService_RemoveTrustedKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginAdminServiceServer).RemoveTrustedKey(ctx, req.(*RemoveTrustedKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginAdminService_ListTrustedKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTrustedKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginAdminServiceServer).ListTrustedKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginAdminService_ListTrustedKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginAdminServiceServer).ListTrustedKeys(ctx, req.(*ListTrustedKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginAdminService_ServiceDesc is the grpc.ServiceDesc for PluginAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cipherlake.plugin.PluginAdminService",
	HandlerType: (*PluginAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InstallPlugin",
			Handler:    _PluginAdminService_InstallPlugin_Handler,
		},
		{
			MethodName: "UninstallPlugin",
			Handler:    _PluginAdminService_UninstallPlugin_Handler,
		},
		{
			MethodName: "ReloadPlugin",
			Handler:    _PluginAdminService_ReloadPlugin_Handler,
		},
		{
			MethodName: "ListPlugins",
			Handler:    _PluginAdminService_ListPlugins_Handler,
		},
		{
			MethodName: "GetPluginState",
			Handler:    _PluginAdminService_GetPluginState_Handler,
		},
		{
			MethodName: "DumpPluginState",
			Handler:    _PluginAdminService_DumpPluginState_Handler,
		},
		{
			MethodName: "GetPluginLogs",
			Handler:    _PluginAdminService_GetPluginLogs_Handler,
		},
		{
			MethodName: "GetPluginMetrics",
			Handler:    _PluginAdminService_GetPluginMetrics_Handler,
		},
		{
			MethodName: "SetPluginLogLevel",
			Handler:    _PluginAdminService_SetPluginLogLevel_Handler,
		},
		{
			MethodName: "AddTrustedKey",
			Handler:    _PluginAdminService_AddTrustedKey_Handler,
		},
		{
			MethodName: "RemoveTrustedKey",
			Handler:    _PluginAdminService_RemoveTrustedKey_Handler,
		},
		{
			MethodName: "ListTrustedKeys",
			Handler:    _PluginAdminService_ListTrustedKeys_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/plugin/admin.proto",
}
