// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/plugin/admin.proto

package plugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstallPluginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OCI artifact URL. When set, the loader pulls the artifact from the
	// configured registry (P3-3). For Phase 3 P3-1 this field is left empty
	// and manifest_bytes/wasm_bytes are used instead.
	OciUrl string `protobuf:"bytes,1,opt,name=oci_url,json=ociUrl,proto3" json:"oci_url,omitempty"`
	// Raw manifest JSON. Required when oci_url is empty.
	ManifestBytes []byte `protobuf:"bytes,2,opt,name=manifest_bytes,json=manifestBytes,proto3" json:"manifest_bytes,omitempty"`
	// Raw WASM bytecode. Required when oci_url is empty.
	WasmBytes []byte `protobuf:"bytes,3,opt,name=wasm_bytes,json=wasmBytes,proto3" json:"wasm_bytes,omitempty"`
	// Ed25519 signature over manifest_bytes || wasm_bytes. Empty for Tier 0.
	Signature []byte `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	// Key ID from trusted_keys.json used to verify signature. Empty for Tier 0.
	KeyId string `protobuf:"bytes,5,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// Force installation even if route prefixes are already owned. Dangerous;
	// intended for disaster recovery.
	Force         bool `protobuf:"varint,6,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallPluginRequest) Reset() {
	*x = InstallPluginRequest{}
	mi := &file_proto_plugin_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallPluginRequest) ProtoMessage() {}

func (x *InstallPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallPluginRequest.ProtoReflect.Descriptor instead.
func (*InstallPluginRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_admin_proto_rawDescGZIP(), []int{0}
}

func (x *InstallPluginRequest) GetOciUrl() string {
	if x != nil {
		return x.OciUrl
	}
	return ""
}

func (x *InstallPluginRequest) GetManifestBytes() []byte {
	if x != nil {
		return x.ManifestBytes
	}
	return nil
}

func (x *InstallPluginRequest) GetWasmBytes() []byte {
	if x != nil {
		return x.WasmBytes
	}
	return nil
}

func (x *InstallPluginRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *InstallPluginRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *InstallPluginRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type InstallPluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginName    string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	TrustTier     int32                  `protobuf:"varint,3,opt,name=trust_tier,json=trustTier,proto3" json:"trust_tier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallPluginResponse) Reset() {
	*x = InstallPluginResponse{}
	mi := &file_proto_plugin_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallPluginResponse) ProtoMessage() {}

func (x *InstallPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallPluginResponse.ProtoReflect.Descriptor instead.
func (*InstallPluginResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_admin_proto_rawDescGZIP(), []int{1}
}

func (x *InstallPluginResponse) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *InstallPluginResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InstallPluginResponse) GetTrustTier() int32 {
	if x != nil {
		return x.TrustTier
	}
	return 0
}

type UninstallPluginRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	PluginName string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	// Force uninstall even if other plugins declare depends_on this plugin.
	Force         bool `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UninstallPluginRequest) Reset() {
	*x = UninstallPluginRequest{}
	mi := &file_proto_plugin_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UninstallPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UninstallPluginRequest) ProtoMessage() {}

func (x *UninstallPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UninstallPluginRequest.ProtoReflect.Descriptor instead.
func (*UninstallPluginRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_admin_proto_rawDescGZIP(), []int{2}
}

func (x *UninstallPluginRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *UninstallPluginRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type UninstallPluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uninstalled   bool                   `protobuf:"varint,1,opt,name=uninstalled,proto3" json:"uninstalled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UninstallPluginResponse) Reset() {
	*x = UninstallPluginResponse{}
	mi := &file_proto_plugin_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UninstallPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UninstallPluginResponse) ProtoMessage() {}

func (x *UninstallPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UninstallPluginResponse.ProtoReflect.Descriptor instead.
func (*UninstallPluginResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_admin_proto_rawDescGZIP(), []int{3}
}

func (x *UninstallPluginResponse) GetUninstalled() bool {
	if x != nil {
		return x.Uninstalled
	}
	return false
}

type ReloadPluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginName    string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadPluginRequest) Reset() {
	*x = ReloadPluginRequest{}
	mi := &file_proto_plugin_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadPluginRequest) ProtoMessage() {}

func (x *ReloadPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadPluginRequest.ProtoReflect.Descriptor instead.
func (*ReloadPluginRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_admin_proto_rawDescGZIP(), []int{4}
}

func (x *ReloadPluginRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

type ReloadPluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginName    string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	TrustTier     int32                  `protobuf:"varint,3,opt,name=trust_tier,json=trustTier,proto3" json:"trust_tier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadPluginResponse) Reset() {
	*x = ReloadPluginResponse{}
	mi := &file_proto_plugin_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadPluginResponse) ProtoMessage() {}

func (x *ReloadPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadPluginResponse.ProtoReflect.Descriptor instead.
func (*ReloadPluginResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ReloadPluginResponse) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *ReloadPluginResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ReloadPluginResponse) GetTrustTier() int32 {
	if x != nil {
		return x.TrustTier
	}
	return 0
}

type ListPluginsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsRequest) Reset() {
	*x = ListPluginsRequest{}
	mi := &file_proto_plugin_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsRequest) ProtoMessage() {}

func (x *ListPluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsRequest.ProtoReflect.Descriptor instead.
func (*ListPluginsRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_admin_proto_rawDescGZIP(), []int{6}
}

type PluginInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	TrustTier     int32                  `protobuf:"varint,3,opt,name=trust_tier,json=trustTier,proto3" json:"trust_tier,omitempty"`
	InstalledAt   string                 `protobuf:"bytes,4,opt,name=installed_at,json=installedAt,proto3" json:"installed_at,omitempty"`
	Routes        []string               `protobuf:"bytes,5,rep,name=routes,proto3" json:"routes,omitempty"`
	Capabilities  []string               `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_proto_plugin_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_proto_plugin_admin_proto_rawDescGZIP(), []int{7}
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetTrustTier() int32 {
	if x != nil {
		return x.TrustTier
	}
	return 0
}

func (x *PluginInfo) GetInstalledAt() string {
	if x != nil {
		return x.InstalledAt
	}
	return ""
}

func (x *PluginInfo) GetRoutes() []string {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *PluginInfo) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type ListPluginsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugins       []*PluginInfo          `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsResponse) Reset() {
	*x = ListPluginsResponse{}
	mi := &file_proto_plugin_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsResponse) ProtoMessage() {}

func (x *ListPluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsResponse.ProtoReflect.Descriptor instead.
func (*ListPluginsResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_admin_proto_rawDescGZIP(), []int{8}
}

func (x *ListPluginsResponse) GetPlugins() []*PluginInfo {
	if x != nil {
		return x.Plugins
	}
	return nil
}

type GetPluginStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginName    string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPluginStateRequest) Reset() {
	*x = GetPluginStateRequest{}
	mi := &file_proto_plugin_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPluginStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginStateRequest) ProtoMessage() {}

func (x *GetPluginStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginStateRequest.ProtoReflect.Descriptor instead.
func (*GetPluginStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_admin_proto_rawDescGZIP(), []int{9}
}

func (x *GetPluginStateRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *GetPluginStateRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetPluginStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPluginStateResponse) Reset() {
	*x = GetPluginStateResponse{}
	mi := &file_proto_plugin_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPluginStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginStateResponse) ProtoMessage() {}

func (x *GetPluginStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginStateResponse.ProtoReflect.Descriptor instead.
func (*GetPluginStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_admin_proto_rawDescGZIP(), []int{10}
}

func (x *GetPluginStateResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetPluginStateResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetPluginStateResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type DumpPluginStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginName    string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DumpPluginStateRequest) Reset() {
	*x = DumpPluginStateRequest{}
	mi := &file_proto_plugin_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DumpPluginStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DumpPluginStateRequest) ProtoMessage() {}

func (x *DumpPluginStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DumpPluginStateRequest.ProtoReflect.Descriptor instead.
func (*DumpPluginStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_admin_proto_rawDescGZIP(), []int{11}
}

func (x *DumpPluginStateRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

type StateKVEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Version       uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateKVEntry) Reset() {
	*x = StateKVEntry{}
	mi := &file_proto_plugin_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateKVEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateKVEntry) ProtoMessage() {}

func (x *StateKVEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateKVEntry.ProtoReflect.Descriptor instead.
func (*StateKVEntry) Descriptor() ([]byte, []int) {
	return file_proto_plugin_admin_proto_rawDescGZIP(), []int{12}
}

func (x *StateKVEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StateKVEntry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *StateKVEntry) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type DumpPluginStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginName    string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	Entries       []*StateKVEntry        `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DumpPluginStateResponse) Reset() {
	*x = DumpPluginStateResponse{}
	mi := &file_proto_plugin_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DumpPluginStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DumpPluginStateResponse) ProtoMessage() {}

func (x *DumpPluginStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DumpPluginStateResponse.ProtoReflect.Descriptor instead.
func (*DumpPluginStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_admin_proto_rawDescGZIP(), []int{13}
}

func (x *DumpPluginStateResponse) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *DumpPluginStateResponse) GetEntries() []*StateKVEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GetPluginLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginName    string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`   // default 100
	Follow        bool                   `protobuf:"varint,3,opt,name=follow,proto3" json:"follow,omitempty"` // server-side streaming placeholder; single-shot if false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPluginLogsRequest) Reset() {
	*x = GetPluginLogsRequest{}
	mi := &file_proto_plugin_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPluginLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginLogsRequest) ProtoMessage() {}

func (x *GetPluginLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginLogsRequest.ProtoReflect.Descriptor instead.
func (*GetPluginLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_admin_proto_rawDescGZIP(), []int{14}
}

func (x *GetPluginLogsRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *GetPluginLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetPluginLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

type PluginLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginLogEntry) Reset() {
	*x = PluginLogEntry{}
	mi := &file_proto_plugin_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginLogEntry) ProtoMessage() {}

func (x *PluginLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginLogEntry.ProtoReflect.Descriptor instead.
func (*PluginLogEntry) Descriptor() ([]byte, []int) {
	return file_proto_plugin_admin_proto_rawDescGZIP(), []int{15}
}

func (x *PluginLogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *PluginLogEntry) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *PluginLogEntry) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type GetPluginLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginName    string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	Entries       []*PluginLogEntry      `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPluginLogsResponse) Reset() {
	*x = GetPluginLogsResponse{}
	mi := &file_proto_plugin_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPluginLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginLogsResponse) ProtoMessage() {}

func (x *GetPluginLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginLogsResponse.ProtoReflect.Descriptor instead.
func (*GetPluginLogsResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_admin_proto_rawDescGZIP(), []int{16}
}

func (x *GetPluginLogsResponse) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *GetPluginLogsResponse) GetEntries() []*PluginLogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GetPluginMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginName    string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // default 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPluginMetricsRequest) Reset() {
	*x = GetPluginMetricsRequest{}
	mi := &file_proto_plugin_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPluginMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginMetricsRequest) ProtoMessage() {}

func (x *GetPluginMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetPluginMetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_admin_proto_rawDescGZIP(), []int{17}
}

func (x *GetPluginMetricsRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *GetPluginMetricsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PluginMetricSample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	LabelsJson    string                 `protobuf:"bytes,3,opt,name=labels_json,json=labelsJson,proto3" json:"labels_json,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,4,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginMetricSample) Reset() {
	*x = PluginMetricSample{}
	mi := &file_proto_plugin_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginMetricSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginMetricSample) ProtoMessage() {}

func (x *PluginMetricSample) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginMetricSample.ProtoReflect.Descriptor instead.
func (*PluginMetricSample) Descriptor() ([]byte, []int) {
	return file_proto_plugin_admin_proto_rawDescGZIP(), []int{18}
}

func (x *PluginMetricSample) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginMetricSample) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *PluginMetricSample) GetLabelsJson() string {
	if x != nil {
		return x.LabelsJson
	}
	return ""
}

func (x *PluginMetricSample) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type GetPluginMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginName    string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	Samples       []*PluginMetricSample  `protobuf:"bytes,2,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPluginMetricsResponse) Reset() {
	*x = GetPluginMetricsResponse{}
	mi := &file_proto_plugin_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPluginMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginMetricsResponse) ProtoMessage() {}

func (x *GetPluginMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetPluginMetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_admin_proto_rawDescGZIP(), []int{19}
}

func (x *GetPluginMetricsResponse) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *GetPluginMetricsResponse) GetSamples() []*PluginMetricSample {
	if x != nil {
		return x.Samples
	}
	return nil
}

type SetPluginLogLevelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginName    string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"` // debug, info, warn, error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPluginLogLevelRequest) Reset() {
	*x = SetPluginLogLevelRequest{}
	mi := &file_proto_plugin_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPluginLogLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPluginLogLevelRequest) ProtoMessage() {}

func (x *SetPluginLogLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPluginLogLevelRequest.ProtoReflect.Descriptor instead.
func (*SetPluginLogLevelRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_admin_proto_rawDescGZIP(), []int{20}
}

func (x *SetPluginLogLevelRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *SetPluginLogLevelRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type SetPluginLogLevelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginName    string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPluginLogLevelResponse) Reset() {
	*x = SetPluginLogLevelResponse{}
	mi := &file_proto_plugin_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPluginLogLevelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPluginLogLevelResponse) ProtoMessage() {}

func (x *SetPluginLogLevelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPluginLogLevelResponse.ProtoReflect.Descriptor instead.
func (*SetPluginLogLevelResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_admin_proto_rawDescGZIP(), []int{21}
}

func (x *SetPluginLogLevelResponse) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *SetPluginLogLevelResponse) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type AddTrustedKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // base64 ed25519 public key
	IsCore        bool                   `protobuf:"varint,3,opt,name=is_core,json=isCore,proto3" json:"is_core,omitempty"`
	AddedBy       string                 `protobuf:"bytes,4,opt,name=added_by,json=addedBy,proto3" json:"added_by,omitempty"` // admin user identifier
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTrustedKeyRequest) Reset() {
	*x = AddTrustedKeyRequest{}
	mi := &file_proto_plugin_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTrustedKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTrustedKeyRequest) ProtoMessage() {}

func (x *AddTrustedKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTrustedKeyRequest.ProtoReflect.Descriptor instead.
func (*AddTrustedKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_admin_proto_rawDescGZIP(), []int{22}
}

func (x *AddTrustedKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *AddTrustedKeyRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *AddTrustedKeyRequest) GetIsCore() bool {
	if x != nil {
		return x.IsCore
	}
	return false
}

func (x *AddTrustedKeyRequest) GetAddedBy() string {
	if x != nil {
		return x.AddedBy
	}
	return ""
}

type AddTrustedKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Added         bool                   `protobuf:"varint,2,opt,name=added,proto3" json:"added,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTrustedKeyResponse) Reset() {
	*x = AddTrustedKeyResponse{}
	mi := &file_proto_plugin_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTrustedKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTrustedKeyResponse) ProtoMessage() {}

func (x *AddTrustedKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTrustedKeyResponse.ProtoReflect.Descriptor instead.
func (*AddTrustedKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_admin_proto_rawDescGZIP(), []int{23}
}

func (x *AddTrustedKeyResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *AddTrustedKeyResponse) GetAdded() bool {
	if x != nil {
		return x.Added
	}
	return false
}

type RemoveTrustedKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTrustedKeyRequest) Reset() {
	*x = RemoveTrustedKeyRequest{}
	mi := &file_proto_plugin_admin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTrustedKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTrustedKeyRequest) ProtoMessage() {}

func (x *RemoveTrustedKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_admin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTrustedKeyRequest.ProtoReflect.Descriptor instead.
func (*RemoveTrustedKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_admin_proto_rawDescGZIP(), []int{24}
}

func (x *RemoveTrustedKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type RemoveTrustedKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Removed       bool                   `protobuf:"varint,2,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTrustedKeyResponse) Reset() {
	*x = RemoveTrustedKeyResponse{}
	mi := &file_proto_plugin_admin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTrustedKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTrustedKeyResponse) ProtoMessage() {}

func (x *RemoveTrustedKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_admin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTrustedKeyResponse.ProtoReflect.Descriptor instead.
func (*RemoveTrustedKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_admin_proto_rawDescGZIP(), []int{25}
}

func (x *RemoveTrustedKeyResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *RemoveTrustedKeyResponse) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

type ListTrustedKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTrustedKeysRequest) Reset() {
	*x = ListTrustedKeysRequest{}
	mi := &file_proto_plugin_admin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTrustedKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrustedKeysRequest) ProtoMessage() {}

func (x *ListTrustedKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_admin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrustedKeysRequest.ProtoReflect.Descriptor instead.
func (*ListTrustedKeysRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_admin_proto_rawDescGZIP(), []int{26}
}

type TrustedKeyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	IsCore        bool                   `protobuf:"varint,3,opt,name=is_core,json=isCore,proto3" json:"is_core,omitempty"`
	AddedAt       string                 `protobuf:"bytes,4,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`
	AddedBy       string                 `protobuf:"bytes,5,opt,name=added_by,json=addedBy,proto3" json:"added_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrustedKeyInfo) Reset() {
	*x = TrustedKeyInfo{}
	mi := &file_proto_plugin_admin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustedKeyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustedKeyInfo) ProtoMessage() {}

func (x *TrustedKeyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_admin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustedKeyInfo.ProtoReflect.Descriptor instead.
func (*TrustedKeyInfo) Descriptor() ([]byte, []int) {
	return file_proto_plugin_admin_proto_rawDescGZIP(), []int{27}
}

func (x *TrustedKeyInfo) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *TrustedKeyInfo) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *TrustedKeyInfo) GetIsCore() bool {
	if x != nil {
		return x.IsCore
	}
	return false
}

func (x *TrustedKeyInfo) GetAddedAt() string {
	if x != nil {
		return x.AddedAt
	}
	return ""
}

func (x *TrustedKeyInfo) GetAddedBy() string {
	if x != nil {
		return x.AddedBy
	}
	return ""
}

type ListTrustedKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*TrustedKeyInfo      `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTrustedKeysResponse) Reset() {
	*x = ListTrustedKeysResponse{}
	mi := &file_proto_plugin_admin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTrustedKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrustedKeysResponse) ProtoMessage() {}

func (x *ListTrustedKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_admin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrustedKeysResponse.ProtoReflect.Descriptor instead.
func (*ListTrustedKeysResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_admin_proto_rawDescGZIP(), []int{28}
}

func (x *ListTrustedKeysResponse) GetKeys() []*TrustedKeyInfo {
	if x != nil {
		return x.Keys
	}
	return nil
}

var File_proto_plugin_admin_proto protoreflect.FileDescriptor

const file_proto_plugin_admin_proto_rawDesc = "" +
	"\n" +
	"\x18proto/plugin/admin.proto\x12\x11cipherlake.plugin\"\xc0\x01\n" +
	"\x14InstallPluginRequest\x12\x17\n" +
	"\aoci_url\x18\x01 \x01(\tR\x06ociUrl\x12%\n" +
	"\x0emanifest_bytes\x18\x02 \x01(\fR\rmanifestBytes\x12\x1d\n" +
	"\n" +
	"wasm_bytes\x18\x03 \x01(\fR\twasmBytes\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\x12\x15\n" +
	"\x06key_id\x18\x05 \x01(\tR\x05keyId\x12\x14\n" +
	"\x05force\x18\x06 \x01(\bR\x05force\"q\n" +
	"\x15InstallPluginResponse\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"trust_tier\x18\x03 \x01(\x05R\ttrustTier\"O\n" +
	"\x16UninstallPluginRequest\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\";\n" +
	"\x17UninstallPluginResponse\x12 \n" +
	"\vuninstalled\x18\x01 \x01(\bR\vuninstalled\"6\n" +
	"\x13ReloadPluginRequest\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\"p\n" +
	"\x14ReloadPluginResponse\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"trust_tier\x18\x03 \x01(\x05R\ttrustTier\"\x14\n" +
	"\x12ListPluginsRequest\"\xb8\x01\n" +
	"\n" +
	"PluginInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"trust_tier\x18\x03 \x01(\x05R\ttrustTier\x12!\n" +
	"\finstalled_at\x18\x04 \x01(\tR\vinstalledAt\x12\x16\n" +
	"\x06routes\x18\x05 \x03(\tR\x06routes\x12\"\n" +
	"\fcapabilities\x18\x06 \x03(\tR\fcapabilities\"N\n" +
	"\x13ListPluginsResponse\x127\n" +
	"\aplugins\x18\x01 \x03(\v2\x1d.cipherlake.plugin.PluginInfoR\aplugins\"J\n" +
	"\x15GetPluginStateRequest\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"^\n" +
	"\x16GetPluginStateResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\"9\n" +
	"\x16DumpPluginStateRequest\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\"P\n" +
	"\fStateKVEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\"u\n" +
	"\x17DumpPluginStateResponse\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x129\n" +
	"\aentries\x18\x02 \x03(\v2\x1f.cipherlake.plugin.StateKVEntryR\aentries\"e\n" +
	"\x14GetPluginLogsRequest\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06follow\x18\x03 \x01(\bR\x06follow\"c\n" +
	"\x0ePluginLogEntry\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\"u\n" +
	"\x15GetPluginLogsResponse\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12;\n" +
	"\aentries\x18\x02 \x03(\v2!.cipherlake.plugin.PluginLogEntryR\aentries\"P\n" +
	"\x17GetPluginMetricsRequest\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x82\x01\n" +
	"\x12PluginMetricSample\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x1f\n" +
	"\vlabels_json\x18\x03 \x01(\tR\n" +
	"labelsJson\x12!\n" +
	"\ftimestamp_ms\x18\x04 \x01(\x03R\vtimestampMs\"|\n" +
	"\x18GetPluginMetricsResponse\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12?\n" +
	"\asamples\x18\x02 \x03(\v2%.cipherlake.plugin.PluginMetricSampleR\asamples\"Q\n" +
	"\x18SetPluginLogLevelRequest\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\"R\n" +
	"\x19SetPluginLogLevelResponse\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\"\x80\x01\n" +
	"\x14AddTrustedKeyRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x17\n" +
	"\ais_core\x18\x03 \x01(\bR\x06isCore\x12\x19\n" +
	"\badded_by\x18\x04 \x01(\tR\aaddedBy\"D\n" +
	"\x15AddTrustedKeyResponse\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x14\n" +
	"\x05added\x18\x02 \x01(\bR\x05added\"0\n" +
	"\x17RemoveTrustedKeyRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\"K\n" +
	"\x18RemoveTrustedKeyResponse\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x18\n" +
	"\aremoved\x18\x02 \x01(\bR\aremoved\"\x18\n" +
	"\x16ListTrustedKeysRequest\"\x95\x01\n" +
	"\x0eTrustedKeyInfo\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x17\n" +
	"\ais_core\x18\x03 \x01(\bR\x06isCore\x12\x19\n" +
	"\badded_at\x18\x04 \x01(\tR\aaddedAt\x12\x19\n" +
	"\badded_by\x18\x05 \x01(\tR\aaddedBy\"P\n" +
	"\x17ListTrustedKeysResponse\x125\n" +
	"\x04keys\x18\x01 \x03(\v2!.cipherlake.plugin.TrustedKeyInfoR\x04keys2\xee\t\n" +
	"\x12PluginAdminService\x12b\n" +
	"\rInstallPlugin\x12'.cipherlake.plugin.InstallPluginRequest\x1a(.cipherlake.plugin.InstallPluginResponse\x12h\n" +
	"\x0fUninstallPlugin\x12).cipherlake.plugin.UninstallPluginRequest\x1a*.cipherlake.plugin.UninstallPluginResponse\x12_\n" +
	"\fReloadPlugin\x12&.cipherlake.plugin.ReloadPluginRequest\x1a'.cipherlake.plugin.ReloadPluginResponse\x12\\\n" +
	"\vListPlugins\x12%.cipherlake.plugin.ListPluginsRequest\x1a&.cipherlake.plugin.ListPluginsResponse\x12e\n" +
	"\x0eGetPluginState\x12(.cipherlake.plugin.GetPluginStateRequest\x1a).cipherlake.plugin.GetPluginStateResponse\x12h\n" +
	"\x0fDumpPluginState\x12).cipherlake.plugin.DumpPluginStateRequest\x1a*.cipherlake.plugin.DumpPluginStateResponse\x12b\n" +
	"\rGetPluginLogs\x12'.cipherlake.plugin.GetPluginLogsRequest\x1a(.cipherlake.plugin.GetPluginLogsResponse\x12k\n" +
	"\x10GetPluginMetrics\x12*.cipherlake.plugin.GetPluginMetricsRequest\x1a+.cipherlake.plugin.GetPluginMetricsResponse\x12n\n" +
	"\x11SetPluginLogLevel\x12+.cipherlake.plugin.SetPluginLogLevelRequest\x1a,.cipherlake.plugin.SetPluginLogLevelResponse\x12b\n" +
	"\rAddTrustedKey\x12'.cipherlake.plugin.AddTrustedKeyRequest\x1a(.cipherlake.plugin.AddTrustedKeyResponse\x12k\n" +
	"\x10RemoveTrustedKey\x12*.cipherlake.plugin.RemoveTrustedKeyRequest\x1a+.cipherlake.plugin.RemoveTrustedKeyResponse\x12h\n" +
	"\x0fListTrustedKeys\x12).cipherlake.plugin.ListTrustedKeysRequest\x1a*.cipherlake.plugin.ListTrustedKeysResponseB\x19Z\x17cipherlake/proto/pluginb\x06proto3"

var (
	file_proto_plugin_admin_proto_rawDescOnce sync.Once
	file_proto_plugin_admin_proto_rawDescData []byte
)

func file_proto_plugin_admin_proto_rawDescGZIP() []byte {
	file_proto_plugin_admin_proto_rawDescOnce.Do(func() {
		file_proto_plugin_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_plugin_admin_proto_rawDesc), len(file_proto_plugin_admin_proto_rawDesc)))
	})
	return file_proto_plugin_admin_proto_rawDescData
}

var file_proto_plugin_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_proto_plugin_admin_proto_goTypes = []any{
	(*InstallPluginRequest)(nil),      // 0: cipherlake.plugin.InstallPluginRequest
	(*InstallPluginResponse)(nil),     // 1: cipherlake.plugin.InstallPluginResponse
	(*UninstallPluginRequest)(nil),    // 2: cipherlake.plugin.UninstallPluginRequest
	(*UninstallPluginResponse)(nil),   // 3: cipherlake.plugin.UninstallPluginResponse
	(*ReloadPluginRequest)(nil),       // 4: cipherlake.plugin.ReloadPluginRequest
	(*ReloadPluginResponse)(nil),      // 5: cipherlake.plugin.ReloadPluginResponse
	(*ListPluginsRequest)(nil),        // 6: cipherlake.plugin.ListPluginsRequest
	(*PluginInfo)(nil),                // 7: cipherlake.plugin.PluginInfo
	(*ListPluginsResponse)(nil),       // 8: cipherlake.plugin.ListPluginsResponse
	(*GetPluginStateRequest)(nil),     // 9: cipherlake.plugin.GetPluginStateRequest
	(*GetPluginStateResponse)(nil),    // 10: cipherlake.plugin.GetPluginStateResponse
	(*DumpPluginStateRequest)(nil),    // 11: cipherlake.plugin.DumpPluginStateRequest
	(*StateKVEntry)(nil),              // 12: cipherlake.plugin.StateKVEntry
	(*DumpPluginStateResponse)(nil),   // 13: cipherlake.plugin.DumpPluginStateResponse
	(*GetPluginLogsRequest)(nil),      // 14: cipherlake.plugin.GetPluginLogsRequest
	(*PluginLogEntry)(nil),            // 15: cipherlake.plugin.PluginLogEntry
	(*GetPluginLogsResponse)(nil),     // 16: cipherlake.plugin.GetPluginLogsResponse
	(*GetPluginMetricsRequest)(nil),   // 17: cipherlake.plugin.GetPluginMetricsRequest
	(*PluginMetricSample)(nil),        // 18: cipherlake.plugin.PluginMetricSample
	(*GetPluginMetricsResponse)(nil),  // 19: cipherlake.plugin.GetPluginMetricsResponse
	(*SetPluginLogLevelRequest)(nil),  // 20: cipherlake.plugin.SetPluginLogLevelRequest
	(*SetPluginLogLevelResponse)(nil), // 21: cipherlake.plugin.SetPluginLogLevelResponse
	(*AddTrustedKeyRequest)(nil),      // 22: cipherlake.plugin.AddTrustedKeyRequest
	(*AddTrustedKeyResponse)(nil),     // 23: cipherlake.plugin.AddTrustedKeyResponse
	(*RemoveTrustedKeyRequest)(nil),   // 24: cipherlake.plugin.RemoveTrustedKeyRequest
	(*RemoveTrustedKeyResponse)(nil),  // 25: cipherlake.plugin.RemoveTrustedKeyResponse
	(*ListTrustedKeysRequest)(nil),    // 26: cipherlake.plugin.ListTrustedKeysRequest
	(*TrustedKeyInfo)(nil),            // 27: cipherlake.plugin.TrustedKeyInfo
	(*ListTrustedKeysResponse)(nil),   // 28: cipherlake.plugin.ListTrustedKeysResponse
}
var file_proto_plugin_admin_proto_depIdxs = []int32{
	7,  // 0: cipherlake.plugin.ListPluginsResponse.plugins:type_name -> cipherlake.plugin.PluginInfo
	12, // 1: cipherlake.plugin.DumpPluginStateResponse.entries:type_name -> cipherlake.plugin.StateKVEntry
	15, // 2: cipherlake.plugin.GetPluginLogsResponse.entries:type_name -> cipherlake.plugin.PluginLogEntry
	18, // 3: cipherlake.plugin.GetPluginMetricsResponse.samples:type_name -> cipherlake.plugin.PluginMetricSample
	27, // 4: cipherlake.plugin.ListTrustedKeysResponse.keys:type_name -> cipherlake.plugin.TrustedKeyInfo
	0,  // 5: cipherlake.plugin.PluginAdminService.InstallPlugin:input_type -> cipherlake.plugin.InstallPluginRequest
	2,  // 6: cipherlake.plugin.PluginAdminService.UninstallPlugin:input_type -> cipherlake.plugin.UninstallPluginRequest
	4,  // 7: cipherlake.plugin.PluginAdminService.ReloadPlugin:input_type -> cipherlake.plugin.ReloadPluginRequest
	6,  // 8: cipherlake.plugin.PluginAdminService.ListPlugins:input_type -> cipherlake.plugin.ListPluginsRequest
	9,  // 9: cipherlake.plugin.PluginAdminService.GetPluginState:input_type -> cipherlake.plugin.GetPluginStateRequest
	11, // 10: cipherlake.plugin.PluginAdminService.DumpPluginState:input_type -> cipherlake.plugin.DumpPluginStateRequest
	14, // 11: cipherlake.plugin.PluginAdminService.GetPluginLogs:input_type -> cipherlake.plugin.GetPluginLogsRequest
	17, // 12: cipherlake.plugin.PluginAdminService.GetPluginMetrics:input_type -> cipherlake.plugin.GetPluginMetricsRequest
	20, // 13: cipherlake.plugin.PluginAdminService.SetPluginLogLevel:input_type -> cipherlake.plugin.SetPluginLogLevelRequest
	22, // 14: cipherlake.plugin.PluginAdminService.AddTrustedKey:input_type -> cipherlake.plugin.AddTrustedKeyRequest
	24, // 15: cipherlake.plugin.PluginAdminService.RemoveTrustedKey:input_type -> cipherlake.plugin.RemoveTrustedKeyRequest
	26, // 16: cipherlake.plugin.PluginAdminService.ListTrustedKeys:input_type -> cipherlake.plugin.ListTrustedKeysRequest
	1,  // 17: cipherlake.plugin.PluginAdminService.InstallPlugin:output_type -> cipherlake.plugin.InstallPluginResponse
	3,  // 18: cipherlake.plugin.PluginAdminService.UninstallPlugin:output_type -> cipherlake.plugin.UninstallPluginResponse
	5,  // 19: cipherlake.plugin.PluginAdminService.ReloadPlugin:output_type -> cipherlake.plugin.ReloadPluginResponse
	8,  // 20: cipherlake.plugin.PluginAdminService.ListPlugins:output_type -> cipherlake.plugin.ListPluginsResponse
	10, // 21: cipherlake.plugin.PluginAdminService.GetPluginState:output_type -> cipherlake.plugin.GetPluginStateResponse
	13, // 22: cipherlake.plugin.PluginAdminService.DumpPluginState:output_type -> cipherlake.plugin.DumpPluginStateResponse
	16, // 23: cipherlake.plugin.PluginAdminService.GetPluginLogs:output_type -> cipherlake.plugin.GetPluginLogsResponse
	19, // 24: cipherlake.plugin.PluginAdminService.GetPluginMetrics:output_type -> cipherlake.plugin.GetPluginMetricsResponse
	21, // 25: cipherlake.plugin.PluginAdminService.SetPluginLogLevel:output_type -> cipherlake.plugin.SetPluginLogLevelResponse
	23, // 26: cipherlake.plugin.PluginAdminService.AddTrustedKey:output_type -> cipherlake.plugin.AddTrustedKeyResponse
	25, // 27: cipherlake.plugin.PluginAdminService.RemoveTrustedKey:output_type -> cipherlake.plugin.RemoveTrustedKeyResponse
	28, // 28: cipherlake.plugin.PluginAdminService.ListTrustedKeys:output_type -> cipherlake.plugin.ListTrustedKeysResponse
	17, // [17:29] is the sub-list for method output_type
	5,  // [5:17] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_plugin_admin_proto_init() }
func file_proto_plugin_admin_proto_init() {
	if File_proto_plugin_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_plugin_admin_proto_rawDesc), len(file_proto_plugin_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_plugin_admin_proto_goTypes,
		DependencyIndexes: file_proto_plugin_admin_proto_depIdxs,
		MessageInfos:      file_proto_plugin_admin_proto_msgTypes,
	}.Build()
	File_proto_plugin_admin_proto = out.File
	file_proto_plugin_admin_proto_goTypes = nil
	file_proto_plugin_admin_proto_depIdxs = nil
}
