// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.2
// source: proto/plugin/loader.proto

package plugin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginLoaderService_InvokeRoute_FullMethodName = "/cipherlake.plugin.PluginLoaderService/InvokeRoute"
	PluginLoaderService_InvokeHook_FullMethodName  = "/cipherlake.plugin.PluginLoaderService/InvokeHook"
	PluginLoaderService_ListHooks_FullMethodName   = "/cipherlake.plugin.PluginLoaderService/ListHooks"
	PluginLoaderService_Health_FullMethodName      = "/cipherlake.plugin.PluginLoaderService/Health"
)

// PluginLoaderServiceClient is the client API for PluginLoaderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PluginLoaderService is the Gateway-facing API of the plugin-loader
// microservice. It exposes plugin route dispatch and (in later phases)
// hook invocation and admin operations.
type PluginLoaderServiceClient interface {
	// InvokeRoute dispatches an HTTP request that arrived at the Gateway
	// under /_plugins/<plugin_name>/* to the named plugin's on_request
	// entry point. The loader handles sub-routing inside the plugin.
	InvokeRoute(ctx context.Context, in *InvokeRouteRequest, opts ...grpc.CallOption) (*InvokeRouteResponse, error)
	// InvokeHook dispatches a single S3 hook call to a plugin's on_hook
	// entry point (spec §3.2). The Gateway orchestrator calls this for
	// each before/after/around stage in the onion chain.
	InvokeHook(ctx context.Context, in *InvokeHookRequest, opts ...grpc.CallOption) (*InvokeHookResponse, error)
	// ListHooks returns the registered S3 hooks visible to this Gateway.
	// The Gateway uses this to build its local hook orchestrator view.
	ListHooks(ctx context.Context, in *ListHooksRequest, opts ...grpc.CallOption) (*ListHooksResponse, error)
	// Health check.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type pluginLoaderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginLoaderServiceClient(cc grpc.ClientConnInterface) PluginLoaderServiceClient {
	return &pluginLoaderServiceClient{cc}
}

func (c *pluginLoaderServiceClient) InvokeRoute(ctx context.Context, in *InvokeRouteRequest, opts ...grpc.CallOption) (*InvokeRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeRouteResponse)
	err := c.cc.Invoke(ctx, PluginLoaderService_InvokeRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginLoaderServiceClient) InvokeHook(ctx context.Context, in *InvokeHookRequest, opts ...grpc.CallOption) (*InvokeHookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeHookResponse)
	err := c.cc.Invoke(ctx, PluginLoaderService_InvokeHook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginLoaderServiceClient) ListHooks(ctx context.Context, in *ListHooksRequest, opts ...grpc.CallOption) (*ListHooksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHooksResponse)
	err := c.cc.Invoke(ctx, PluginLoaderService_ListHooks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginLoaderServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, PluginLoaderService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginLoaderServiceServer is the server API for PluginLoaderService service.
// All implementations must embed UnimplementedPluginLoaderServiceServer
// for forward compatibility.
//
// PluginLoaderService is the Gateway-facing API of the plugin-loader
// microservice. It exposes plugin route dispatch and (in later phases)
// hook invocation and admin operations.
type PluginLoaderServiceServer interface {
	// InvokeRoute dispatches an HTTP request that arrived at the Gateway
	// under /_plugins/<plugin_name>/* to the named plugin's on_request
	// entry point. The loader handles sub-routing inside the plugin.
	InvokeRoute(context.Context, *InvokeRouteRequest) (*InvokeRouteResponse, error)
	// InvokeHook dispatches a single S3 hook call to a plugin's on_hook
	// entry point (spec §3.2). The Gateway orchestrator calls this for
	// each before/after/around stage in the onion chain.
	InvokeHook(context.Context, *InvokeHookRequest) (*InvokeHookResponse, error)
	// ListHooks returns the registered S3 hooks visible to this Gateway.
	// The Gateway uses this to build its local hook orchestrator view.
	ListHooks(context.Context, *ListHooksRequest) (*ListHooksResponse, error)
	// Health check.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedPluginLoaderServiceServer()
}

// UnimplementedPluginLoaderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginLoaderServiceServer struct{}

func (UnimplementedPluginLoaderServiceServer) InvokeRoute(context.Context, *InvokeRouteRequest) (*InvokeRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InvokeRoute not implemented")
}
func (UnimplementedPluginLoaderServiceServer) InvokeHook(context.Context, *InvokeHookRequest) (*InvokeHookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InvokeHook not implemented")
}
func (UnimplementedPluginLoaderServiceServer) ListHooks(context.Context, *ListHooksRequest) (*ListHooksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHooks not implemented")
}
func (UnimplementedPluginLoaderServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedPluginLoaderServiceServer) mustEmbedUnimplementedPluginLoaderServiceServer() {}
func (UnimplementedPluginLoaderServiceServer) testEmbeddedByValue()                             {}

// UnsafePluginLoaderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginLoaderServiceServer will
// result in compilation errors.
type UnsafePluginLoaderServiceServer interface {
	mustEmbedUnimplementedPluginLoaderServiceServer()
}

func RegisterPluginLoaderServiceServer(s grpc.ServiceRegistrar, srv PluginLoaderServiceServer) {
	// If the following call panics, it indicates UnimplementedPluginLoaderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginLoaderService_ServiceDesc, srv)
}

func _PluginLoaderService_InvokeRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginLoaderServiceServer).InvokeRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginLoaderService_InvokeRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginLoaderServiceServer).InvokeRoute(ctx, req.(*InvokeRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginLoaderService_InvokeHook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeHookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginLoaderServiceServer).InvokeHook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginLoaderService_InvokeHook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginLoaderServiceServer).InvokeHook(ctx, req.(*InvokeHookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginLoaderService_ListHooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginLoaderServiceServer).ListHooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginLoaderService_ListHooks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginLoaderServiceServer).ListHooks(ctx, req.(*ListHooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginLoaderService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginLoaderServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginLoaderService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginLoaderServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginLoaderService_ServiceDesc is the grpc.ServiceDesc for PluginLoaderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginLoaderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cipherlake.plugin.PluginLoaderService",
	HandlerType: (*PluginLoaderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InvokeRoute",
			Handler:    _PluginLoaderService_InvokeRoute_Handler,
		},
		{
			MethodName: "InvokeHook",
			Handler:    _PluginLoaderService_InvokeHook_Handler,
		},
		{
			MethodName: "ListHooks",
			Handler:    _PluginLoaderService_ListHooks_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _PluginLoaderService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/plugin/loader.proto",
}
