// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: plugin/loader.proto

package plugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvokeRouteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Plugin name (must match an installed plugin).
	PluginName string `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	// HTTP method of the incoming request.
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// Path under the plugin prefix, e.g. for /_plugins/foo/bar/baz this
	// is "bar/baz". The leading plugin prefix is stripped by the Gateway.
	Path string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// Original Host header (used for virtual-hosted-style reconstruction).
	Host string `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	// Serialized HTTP headers. Multiple values for the same key are
	// joined with commas per RFC 7230.
	Headers map[string]string `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Request body. For streaming bodies larger than the configured gRPC
	// message limit, the Gateway will buffer or reject; Phase 1 keeps it
	// simple and in-memory.
	Body []byte `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	// Identity of the original caller (from Gateway auth). Passed to the
	// plugin as x-nexus-original-user and forwarded to backend services
	// (spec §2.2 A14).
	OriginalUser  string `protobuf:"bytes,7,opt,name=original_user,json=originalUser,proto3" json:"original_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRouteRequest) Reset() {
	*x = InvokeRouteRequest{}
	mi := &file_plugin_loader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRouteRequest) ProtoMessage() {}

func (x *InvokeRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_loader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRouteRequest.ProtoReflect.Descriptor instead.
func (*InvokeRouteRequest) Descriptor() ([]byte, []int) {
	return file_plugin_loader_proto_rawDescGZIP(), []int{0}
}

func (x *InvokeRouteRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *InvokeRouteRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *InvokeRouteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *InvokeRouteRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *InvokeRouteRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *InvokeRouteRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *InvokeRouteRequest) GetOriginalUser() string {
	if x != nil {
		return x.OriginalUser
	}
	return ""
}

type InvokeRouteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTTP status code to return to the client.
	StatusCode int32 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	// Response headers.
	Headers map[string]string `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Response body.
	Body []byte `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	// Human-readable error message when status_code >= 500.
	ErrorMessage  string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRouteResponse) Reset() {
	*x = InvokeRouteResponse{}
	mi := &file_plugin_loader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRouteResponse) ProtoMessage() {}

func (x *InvokeRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_loader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRouteResponse.ProtoReflect.Descriptor instead.
func (*InvokeRouteResponse) Descriptor() ([]byte, []int) {
	return file_plugin_loader_proto_rawDescGZIP(), []int{1}
}

func (x *InvokeRouteResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *InvokeRouteResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *InvokeRouteResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *InvokeRouteResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_plugin_loader_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_loader_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_plugin_loader_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_plugin_loader_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_loader_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_plugin_loader_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

var File_plugin_loader_proto protoreflect.FileDescriptor

const file_plugin_loader_proto_rawDesc = "" +
	"\n" +
	"\x13plugin/loader.proto\x12\x11cipherlake.plugin\"\xb8\x02\n" +
	"\x12InvokeRouteRequest\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x12\n" +
	"\x04host\x18\x04 \x01(\tR\x04host\x12L\n" +
	"\aheaders\x18\x05 \x03(\v22.cipherlake.plugin.InvokeRouteRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x06 \x01(\fR\x04body\x12#\n" +
	"\roriginal_user\x18\a \x01(\tR\foriginalUser\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfa\x01\n" +
	"\x13InvokeRouteResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12M\n" +
	"\aheaders\x18\x02 \x03(\v23.cipherlake.plugin.InvokeRouteResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x0f\n" +
	"\rHealthRequest\"\x8e\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds2\xc2\x01\n" +
	"\x13PluginLoaderService\x12\\\n" +
	"\vInvokeRoute\x12%.cipherlake.plugin.InvokeRouteRequest\x1a&.cipherlake.plugin.InvokeRouteResponse\x12M\n" +
	"\x06Health\x12 .cipherlake.plugin.HealthRequest\x1a!.cipherlake.plugin.HealthResponseB\x19Z\x17cipherlake/proto/pluginb\x06proto3"

var (
	file_plugin_loader_proto_rawDescOnce sync.Once
	file_plugin_loader_proto_rawDescData []byte
)

func file_plugin_loader_proto_rawDescGZIP() []byte {
	file_plugin_loader_proto_rawDescOnce.Do(func() {
		file_plugin_loader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_loader_proto_rawDesc), len(file_plugin_loader_proto_rawDesc)))
	})
	return file_plugin_loader_proto_rawDescData
}

var file_plugin_loader_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_plugin_loader_proto_goTypes = []any{
	(*InvokeRouteRequest)(nil),  // 0: cipherlake.plugin.InvokeRouteRequest
	(*InvokeRouteResponse)(nil), // 1: cipherlake.plugin.InvokeRouteResponse
	(*HealthRequest)(nil),       // 2: cipherlake.plugin.HealthRequest
	(*HealthResponse)(nil),      // 3: cipherlake.plugin.HealthResponse
	nil,                         // 4: cipherlake.plugin.InvokeRouteRequest.HeadersEntry
	nil,                         // 5: cipherlake.plugin.InvokeRouteResponse.HeadersEntry
}
var file_plugin_loader_proto_depIdxs = []int32{
	4, // 0: cipherlake.plugin.InvokeRouteRequest.headers:type_name -> cipherlake.plugin.InvokeRouteRequest.HeadersEntry
	5, // 1: cipherlake.plugin.InvokeRouteResponse.headers:type_name -> cipherlake.plugin.InvokeRouteResponse.HeadersEntry
	0, // 2: cipherlake.plugin.PluginLoaderService.InvokeRoute:input_type -> cipherlake.plugin.InvokeRouteRequest
	2, // 3: cipherlake.plugin.PluginLoaderService.Health:input_type -> cipherlake.plugin.HealthRequest
	1, // 4: cipherlake.plugin.PluginLoaderService.InvokeRoute:output_type -> cipherlake.plugin.InvokeRouteResponse
	3, // 5: cipherlake.plugin.PluginLoaderService.Health:output_type -> cipherlake.plugin.HealthResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_plugin_loader_proto_init() }
func file_plugin_loader_proto_init() {
	if File_plugin_loader_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_loader_proto_rawDesc), len(file_plugin_loader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_loader_proto_goTypes,
		DependencyIndexes: file_plugin_loader_proto_depIdxs,
		MessageInfos:      file_plugin_loader_proto_msgTypes,
	}.Build()
	File_plugin_loader_proto = out.File
	file_plugin_loader_proto_goTypes = nil
	file_plugin_loader_proto_depIdxs = nil
}
