// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/plugin/loader.proto

package plugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HookAction is the result of a single hook invocation.
type HookAction int32

const (
	HookAction_HOOK_ACTION_UNSPECIFIED HookAction = 0
	HookAction_HOOK_ACTION_CONTINUE    HookAction = 1 // proceed to the next hook / inner handler
	HookAction_HOOK_ACTION_ABORT       HookAction = 2 // short-circuit and return the response in this message
	HookAction_HOOK_ACTION_MODIFY      HookAction = 3 // mutate context (request/response) and continue
)

// Enum value maps for HookAction.
var (
	HookAction_name = map[int32]string{
		0: "HOOK_ACTION_UNSPECIFIED",
		1: "HOOK_ACTION_CONTINUE",
		2: "HOOK_ACTION_ABORT",
		3: "HOOK_ACTION_MODIFY",
	}
	HookAction_value = map[string]int32{
		"HOOK_ACTION_UNSPECIFIED": 0,
		"HOOK_ACTION_CONTINUE":    1,
		"HOOK_ACTION_ABORT":       2,
		"HOOK_ACTION_MODIFY":      3,
	}
)

func (x HookAction) Enum() *HookAction {
	p := new(HookAction)
	*p = x
	return p
}

func (x HookAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HookAction) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_plugin_loader_proto_enumTypes[0].Descriptor()
}

func (HookAction) Type() protoreflect.EnumType {
	return &file_proto_plugin_loader_proto_enumTypes[0]
}

func (x HookAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HookAction.Descriptor instead.
func (HookAction) EnumDescriptor() ([]byte, []int) {
	return file_proto_plugin_loader_proto_rawDescGZIP(), []int{0}
}

type InvokeRouteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Plugin name (must match an installed plugin).
	PluginName string `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	// HTTP method of the incoming request.
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// Path under the plugin prefix, e.g. for /_plugins/foo/bar/baz this
	// is "bar/baz". The leading plugin prefix is stripped by the Gateway.
	Path string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// Original Host header (used for virtual-hosted-style reconstruction).
	Host string `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	// Serialized HTTP headers. Multiple values for the same key are
	// joined with commas per RFC 7230.
	Headers map[string]string `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Request body. For streaming bodies larger than the configured gRPC
	// message limit, the Gateway will buffer or reject; Phase 1 keeps it
	// simple and in-memory.
	Body []byte `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	// Identity of the original caller (from Gateway auth). Passed to the
	// plugin as x-nexus-original-user and forwarded to backend services
	// (spec §2.2 A14).
	OriginalUser  string `protobuf:"bytes,7,opt,name=original_user,json=originalUser,proto3" json:"original_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRouteRequest) Reset() {
	*x = InvokeRouteRequest{}
	mi := &file_proto_plugin_loader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRouteRequest) ProtoMessage() {}

func (x *InvokeRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_loader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRouteRequest.ProtoReflect.Descriptor instead.
func (*InvokeRouteRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_loader_proto_rawDescGZIP(), []int{0}
}

func (x *InvokeRouteRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *InvokeRouteRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *InvokeRouteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *InvokeRouteRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *InvokeRouteRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *InvokeRouteRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *InvokeRouteRequest) GetOriginalUser() string {
	if x != nil {
		return x.OriginalUser
	}
	return ""
}

type InvokeRouteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTTP status code to return to the client.
	StatusCode int32 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	// Response headers.
	Headers map[string]string `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Response body.
	Body []byte `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	// Human-readable error message when status_code >= 500.
	ErrorMessage  string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRouteResponse) Reset() {
	*x = InvokeRouteResponse{}
	mi := &file_proto_plugin_loader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRouteResponse) ProtoMessage() {}

func (x *InvokeRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_loader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRouteResponse.ProtoReflect.Descriptor instead.
func (*InvokeRouteResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_loader_proto_rawDescGZIP(), []int{1}
}

func (x *InvokeRouteResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *InvokeRouteResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *InvokeRouteResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *InvokeRouteResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_plugin_loader_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_loader_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_loader_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_plugin_loader_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_loader_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_loader_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

// HookContext carries the S3 operation context passed to a plugin hook.
type HookContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// S3 operation name, e.g. "s3:GetObject".
	Operation string `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	// Hook phase: "before", "after", "around_before", "around_after".
	Phase string `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	// Target bucket and object key (may be empty for bucket-level ops).
	Bucket string `protobuf:"bytes,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key    string `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	// HTTP method of the original request.
	Method string `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	// Serialized HTTP headers.
	Headers map[string]string `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Request or response body (depending on phase).
	Body []byte `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	// Identity of the original caller.
	OriginalUser string `protobuf:"bytes,8,opt,name=original_user,json=originalUser,proto3" json:"original_user,omitempty"`
	// Response status code when phase is "after" or "around_after".
	StatusCode    int32 `protobuf:"varint,9,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookContext) Reset() {
	*x = HookContext{}
	mi := &file_proto_plugin_loader_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookContext) ProtoMessage() {}

func (x *HookContext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_loader_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookContext.ProtoReflect.Descriptor instead.
func (*HookContext) Descriptor() ([]byte, []int) {
	return file_proto_plugin_loader_proto_rawDescGZIP(), []int{4}
}

func (x *HookContext) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *HookContext) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *HookContext) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *HookContext) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HookContext) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HookContext) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HookContext) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HookContext) GetOriginalUser() string {
	if x != nil {
		return x.OriginalUser
	}
	return ""
}

func (x *HookContext) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

type InvokeHookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Plugin that owns the hook.
	PluginName string `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	// Handler entry point in the WASM module (usually "on_hook").
	Handler string `protobuf:"bytes,2,opt,name=handler,proto3" json:"handler,omitempty"`
	// Context passed to the hook.
	Context       *HookContext `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeHookRequest) Reset() {
	*x = InvokeHookRequest{}
	mi := &file_proto_plugin_loader_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeHookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeHookRequest) ProtoMessage() {}

func (x *InvokeHookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_loader_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeHookRequest.ProtoReflect.Descriptor instead.
func (*InvokeHookRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_loader_proto_rawDescGZIP(), []int{5}
}

func (x *InvokeHookRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *InvokeHookRequest) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *InvokeHookRequest) GetContext() *HookContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type InvokeHookResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Action the Gateway orchestrator should take.
	Action HookAction `protobuf:"varint,1,opt,name=action,proto3,enum=cipherlake.plugin.HookAction" json:"action,omitempty"`
	// HTTP status code when action is ABORT or MODIFY on a response.
	StatusCode int32 `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	// Response headers when action is ABORT or MODIFY on a response.
	Headers map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Response body when action is ABORT.
	Body []byte `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	// Mutated request context when action is MODIFY on a request.
	ModifiedContext *HookContext `protobuf:"bytes,5,opt,name=modified_context,json=modifiedContext,proto3" json:"modified_context,omitempty"`
	// Human-readable error when the hook call itself failed.
	ErrorMessage  string `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeHookResponse) Reset() {
	*x = InvokeHookResponse{}
	mi := &file_proto_plugin_loader_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeHookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeHookResponse) ProtoMessage() {}

func (x *InvokeHookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_loader_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeHookResponse.ProtoReflect.Descriptor instead.
func (*InvokeHookResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_loader_proto_rawDescGZIP(), []int{6}
}

func (x *InvokeHookResponse) GetAction() HookAction {
	if x != nil {
		return x.Action
	}
	return HookAction_HOOK_ACTION_UNSPECIFIED
}

func (x *InvokeHookResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *InvokeHookResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *InvokeHookResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *InvokeHookResponse) GetModifiedContext() *HookContext {
	if x != nil {
		return x.ModifiedContext
	}
	return nil
}

func (x *InvokeHookResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ListHooksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filter by operation name (e.g. "s3:GetObject"). Empty = all.
	Operation     string `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHooksRequest) Reset() {
	*x = ListHooksRequest{}
	mi := &file_proto_plugin_loader_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHooksRequest) ProtoMessage() {}

func (x *ListHooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_loader_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHooksRequest.ProtoReflect.Descriptor instead.
func (*ListHooksRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_loader_proto_rawDescGZIP(), []int{7}
}

func (x *ListHooksRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

// HookRecord describes a registered hook as seen by the Gateway.
type HookRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginName    string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	HookId        string                 `protobuf:"bytes,2,opt,name=hook_id,json=hookId,proto3" json:"hook_id,omitempty"`
	HookType      string                 `protobuf:"bytes,3,opt,name=hook_type,json=hookType,proto3" json:"hook_type,omitempty"` // "before" | "after" | "around"
	Operation     string                 `protobuf:"bytes,4,opt,name=operation,proto3" json:"operation,omitempty"`
	Condition     string                 `protobuf:"bytes,5,opt,name=condition,proto3" json:"condition,omitempty"` // CEL expression (not evaluated by Gateway in Phase 2)
	Handler       string                 `protobuf:"bytes,6,opt,name=handler,proto3" json:"handler,omitempty"`
	Priority      int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	OnFailure     string                 `protobuf:"bytes,8,opt,name=on_failure,json=onFailure,proto3" json:"on_failure,omitempty"` // "deny" | "allow" | "log_and_allow"
	Critical      bool                   `protobuf:"varint,9,opt,name=critical,proto3" json:"critical,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookRecord) Reset() {
	*x = HookRecord{}
	mi := &file_proto_plugin_loader_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookRecord) ProtoMessage() {}

func (x *HookRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_loader_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookRecord.ProtoReflect.Descriptor instead.
func (*HookRecord) Descriptor() ([]byte, []int) {
	return file_proto_plugin_loader_proto_rawDescGZIP(), []int{8}
}

func (x *HookRecord) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *HookRecord) GetHookId() string {
	if x != nil {
		return x.HookId
	}
	return ""
}

func (x *HookRecord) GetHookType() string {
	if x != nil {
		return x.HookType
	}
	return ""
}

func (x *HookRecord) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *HookRecord) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *HookRecord) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *HookRecord) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *HookRecord) GetOnFailure() string {
	if x != nil {
		return x.OnFailure
	}
	return ""
}

func (x *HookRecord) GetCritical() bool {
	if x != nil {
		return x.Critical
	}
	return false
}

type ListHooksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hooks         []*HookRecord          `protobuf:"bytes,1,rep,name=hooks,proto3" json:"hooks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHooksResponse) Reset() {
	*x = ListHooksResponse{}
	mi := &file_proto_plugin_loader_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHooksResponse) ProtoMessage() {}

func (x *ListHooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_loader_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHooksResponse.ProtoReflect.Descriptor instead.
func (*ListHooksResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_loader_proto_rawDescGZIP(), []int{9}
}

func (x *ListHooksResponse) GetHooks() []*HookRecord {
	if x != nil {
		return x.Hooks
	}
	return nil
}

var File_proto_plugin_loader_proto protoreflect.FileDescriptor

const file_proto_plugin_loader_proto_rawDesc = "" +
	"\n" +
	"\x19proto/plugin/loader.proto\x12\x11cipherlake.plugin\"\xb8\x02\n" +
	"\x12InvokeRouteRequest\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x12\n" +
	"\x04host\x18\x04 \x01(\tR\x04host\x12L\n" +
	"\aheaders\x18\x05 \x03(\v22.cipherlake.plugin.InvokeRouteRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x06 \x01(\fR\x04body\x12#\n" +
	"\roriginal_user\x18\a \x01(\tR\foriginalUser\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfa\x01\n" +
	"\x13InvokeRouteResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12M\n" +
	"\aheaders\x18\x02 \x03(\v23.cipherlake.plugin.InvokeRouteResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x0f\n" +
	"\rHealthRequest\"\x8e\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds\"\xe0\x02\n" +
	"\vHookContext\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\tR\toperation\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12\x16\n" +
	"\x06bucket\x18\x03 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x12E\n" +
	"\aheaders\x18\x06 \x03(\v2+.cipherlake.plugin.HookContext.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\a \x01(\fR\x04body\x12#\n" +
	"\roriginal_user\x18\b \x01(\tR\foriginalUser\x12\x1f\n" +
	"\vstatus_code\x18\t \x01(\x05R\n" +
	"statusCode\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x88\x01\n" +
	"\x11InvokeHookRequest\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12\x18\n" +
	"\ahandler\x18\x02 \x01(\tR\ahandler\x128\n" +
	"\acontext\x18\x03 \x01(\v2\x1e.cipherlake.plugin.HookContextR\acontext\"\xfa\x02\n" +
	"\x12InvokeHookResponse\x125\n" +
	"\x06action\x18\x01 \x01(\x0e2\x1d.cipherlake.plugin.HookActionR\x06action\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12L\n" +
	"\aheaders\x18\x03 \x03(\v22.cipherlake.plugin.InvokeHookResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12I\n" +
	"\x10modified_context\x18\x05 \x01(\v2\x1e.cipherlake.plugin.HookContextR\x0fmodifiedContext\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"0\n" +
	"\x10ListHooksRequest\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\tR\toperation\"\x90\x02\n" +
	"\n" +
	"HookRecord\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12\x17\n" +
	"\ahook_id\x18\x02 \x01(\tR\x06hookId\x12\x1b\n" +
	"\thook_type\x18\x03 \x01(\tR\bhookType\x12\x1c\n" +
	"\toperation\x18\x04 \x01(\tR\toperation\x12\x1c\n" +
	"\tcondition\x18\x05 \x01(\tR\tcondition\x12\x18\n" +
	"\ahandler\x18\x06 \x01(\tR\ahandler\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\x12\x1d\n" +
	"\n" +
	"on_failure\x18\b \x01(\tR\tonFailure\x12\x1a\n" +
	"\bcritical\x18\t \x01(\bR\bcritical\"H\n" +
	"\x11ListHooksResponse\x123\n" +
	"\x05hooks\x18\x01 \x03(\v2\x1d.cipherlake.plugin.HookRecordR\x05hooks*r\n" +
	"\n" +
	"HookAction\x12\x1b\n" +
	"\x17HOOK_ACTION_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14HOOK_ACTION_CONTINUE\x10\x01\x12\x15\n" +
	"\x11HOOK_ACTION_ABORT\x10\x02\x12\x16\n" +
	"\x12HOOK_ACTION_MODIFY\x10\x032\xf5\x02\n" +
	"\x13PluginLoaderService\x12\\\n" +
	"\vInvokeRoute\x12%.cipherlake.plugin.InvokeRouteRequest\x1a&.cipherlake.plugin.InvokeRouteResponse\x12Y\n" +
	"\n" +
	"InvokeHook\x12$.cipherlake.plugin.InvokeHookRequest\x1a%.cipherlake.plugin.InvokeHookResponse\x12V\n" +
	"\tListHooks\x12#.cipherlake.plugin.ListHooksRequest\x1a$.cipherlake.plugin.ListHooksResponse\x12M\n" +
	"\x06Health\x12 .cipherlake.plugin.HealthRequest\x1a!.cipherlake.plugin.HealthResponseB\x19Z\x17cipherlake/proto/pluginb\x06proto3"

var (
	file_proto_plugin_loader_proto_rawDescOnce sync.Once
	file_proto_plugin_loader_proto_rawDescData []byte
)

func file_proto_plugin_loader_proto_rawDescGZIP() []byte {
	file_proto_plugin_loader_proto_rawDescOnce.Do(func() {
		file_proto_plugin_loader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_plugin_loader_proto_rawDesc), len(file_proto_plugin_loader_proto_rawDesc)))
	})
	return file_proto_plugin_loader_proto_rawDescData
}

var file_proto_plugin_loader_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_plugin_loader_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_plugin_loader_proto_goTypes = []any{
	(HookAction)(0),             // 0: cipherlake.plugin.HookAction
	(*InvokeRouteRequest)(nil),  // 1: cipherlake.plugin.InvokeRouteRequest
	(*InvokeRouteResponse)(nil), // 2: cipherlake.plugin.InvokeRouteResponse
	(*HealthRequest)(nil),       // 3: cipherlake.plugin.HealthRequest
	(*HealthResponse)(nil),      // 4: cipherlake.plugin.HealthResponse
	(*HookContext)(nil),         // 5: cipherlake.plugin.HookContext
	(*InvokeHookRequest)(nil),   // 6: cipherlake.plugin.InvokeHookRequest
	(*InvokeHookResponse)(nil),  // 7: cipherlake.plugin.InvokeHookResponse
	(*ListHooksRequest)(nil),    // 8: cipherlake.plugin.ListHooksRequest
	(*HookRecord)(nil),          // 9: cipherlake.plugin.HookRecord
	(*ListHooksResponse)(nil),   // 10: cipherlake.plugin.ListHooksResponse
	nil,                         // 11: cipherlake.plugin.InvokeRouteRequest.HeadersEntry
	nil,                         // 12: cipherlake.plugin.InvokeRouteResponse.HeadersEntry
	nil,                         // 13: cipherlake.plugin.HookContext.HeadersEntry
	nil,                         // 14: cipherlake.plugin.InvokeHookResponse.HeadersEntry
}
var file_proto_plugin_loader_proto_depIdxs = []int32{
	11, // 0: cipherlake.plugin.InvokeRouteRequest.headers:type_name -> cipherlake.plugin.InvokeRouteRequest.HeadersEntry
	12, // 1: cipherlake.plugin.InvokeRouteResponse.headers:type_name -> cipherlake.plugin.InvokeRouteResponse.HeadersEntry
	13, // 2: cipherlake.plugin.HookContext.headers:type_name -> cipherlake.plugin.HookContext.HeadersEntry
	5,  // 3: cipherlake.plugin.InvokeHookRequest.context:type_name -> cipherlake.plugin.HookContext
	0,  // 4: cipherlake.plugin.InvokeHookResponse.action:type_name -> cipherlake.plugin.HookAction
	14, // 5: cipherlake.plugin.InvokeHookResponse.headers:type_name -> cipherlake.plugin.InvokeHookResponse.HeadersEntry
	5,  // 6: cipherlake.plugin.InvokeHookResponse.modified_context:type_name -> cipherlake.plugin.HookContext
	9,  // 7: cipherlake.plugin.ListHooksResponse.hooks:type_name -> cipherlake.plugin.HookRecord
	1,  // 8: cipherlake.plugin.PluginLoaderService.InvokeRoute:input_type -> cipherlake.plugin.InvokeRouteRequest
	6,  // 9: cipherlake.plugin.PluginLoaderService.InvokeHook:input_type -> cipherlake.plugin.InvokeHookRequest
	8,  // 10: cipherlake.plugin.PluginLoaderService.ListHooks:input_type -> cipherlake.plugin.ListHooksRequest
	3,  // 11: cipherlake.plugin.PluginLoaderService.Health:input_type -> cipherlake.plugin.HealthRequest
	2,  // 12: cipherlake.plugin.PluginLoaderService.InvokeRoute:output_type -> cipherlake.plugin.InvokeRouteResponse
	7,  // 13: cipherlake.plugin.PluginLoaderService.InvokeHook:output_type -> cipherlake.plugin.InvokeHookResponse
	10, // 14: cipherlake.plugin.PluginLoaderService.ListHooks:output_type -> cipherlake.plugin.ListHooksResponse
	4,  // 15: cipherlake.plugin.PluginLoaderService.Health:output_type -> cipherlake.plugin.HealthResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_plugin_loader_proto_init() }
func file_proto_plugin_loader_proto_init() {
	if File_proto_plugin_loader_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_plugin_loader_proto_rawDesc), len(file_proto_plugin_loader_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_plugin_loader_proto_goTypes,
		DependencyIndexes: file_proto_plugin_loader_proto_depIdxs,
		EnumInfos:         file_proto_plugin_loader_proto_enumTypes,
		MessageInfos:      file_proto_plugin_loader_proto_msgTypes,
	}.Build()
	File_proto_plugin_loader_proto = out.File
	file_proto_plugin_loader_proto_goTypes = nil
	file_proto_plugin_loader_proto_depIdxs = nil
}
